### ISSUE TITLE
build.gradle should build the skin packs, not just the resource pack folder used in the mod.

### ISSUE THREAD

**Issue by Sollace** [MineLittlePony/MineLittlePony#105]
We shouldn't expect people to download the repo to get a .zip for the skins pack, especially since you deleted the json files. https://github.com/MineLittlePony/Community-Skin-Pack/issues/3

At the moment the repository currently includes folders for only one skins pack (The Community Pack). In the future this is expected to change as the Fandom/OCs Pack is added.

The build process would have to create separate zip files for each pack only including the relevant folders for each one.

**Comment by killjoy1221** [comment]
Here's your built skinpack jar. https://github.com/MineLittlePony/Community-Skin-Pack/archive/1.7.0-beta.zip
