### ISSUE TITLE
Conflict with wizardry

### ISSUE THREAD

**Issue by Onyx32** [MineLittlePony/MineLittlePony#108]
Hi, I discovered a conflict with the wizardry mod when we click on the button for change the skin.
Crash log : https://paste.dimdev.org/etumoboseh.mccrash

**Comment by Onyx32** [comment]
> Hi, I discovered a conflict with the wizardry mod when we click on the button for change the skin.
> Crash log : https://paste.dimdev.org/etumoboseh.mccrash

**Comment by Onyx32** [comment]
> Hi, I discovered a conflict with the wizardry mod when we click on the button for change the skin.
> Crash log : https://paste.dimdev.org/etumoboseh.mccrash

**Comment by Sollace** [comment]
This looks like a problem on Wizardry's side. Have you reported the crash to them?

**Comment by Sollace** [comment]
Closed for inactivity.
