### ISSUE TITLE
Player has only one wing

### ISSUE THREAD

**Issue by ekevoo** [MineLittlePony/MineLittlePony#11]
I just installed the new release from just a few minutes ago. Thanks. <3

So, my character has no left wing… but there's a right wing?

This is my model: http://ponyskincraft.com/catalog/126431.html

This is what I got.
![2016-07-14_00 51 45](https://cloud.githubusercontent.com/assets/871714/16828416/878a7738-495d-11e6-9e48-806140a1eb9b.png)
![2016-07-14_00 51 50](https://cloud.githubusercontent.com/assets/871714/16828462/f7b2bde0-495d-11e6-8908-3ab880b42385.png)

**Comment by ekevoo** [comment]
My friend who has a pegasus skin (game name is Artaelian) is having the same one-wing problem.

**Comment by ekevoo** [comment]
Here's his skin:
![artaelian](https://cloud.githubusercontent.com/assets/871714/16958962/d50d8002-4db0-11e6-974c-1b0a41ba926f.png)

Here's him with the same problem:
![2016-07-19_17 57 53](https://cloud.githubusercontent.com/assets/871714/16958975/db1a3440-4db0-11e6-93e9-1f242b7655d3.png)

**Comment by killjoy1221** [comment]
Are your skins uploaded via minecraft.net or the HD skin server?

**Comment by ekevoo** [comment]
Yes, they're both uploaded via the official minecraft.net website.

**Comment by CaptainKyros** [comment]
that is your problem

**Comment by ekevoo** [comment]
@CaptainKyros I will interpret this as "retry using the HD server, if it works there, that's not a bug." I'll let you know in a few hour how that goes.

**Comment by killjoy1221** [comment]
It's probably an issue with a broken mixin. I'll investigate in a bit.

**Comment by killjoy1221** [comment]
Try this and see if it works.
https://www.dropbox.com/s/xrv9izxek34acs2/mod-minelittlepony-1.10.2.1-test-mc1.10.2.litemod?dl=0

**Comment by killjoy1221** [comment]
Actually, this should do it.
https://www.dropbox.com/s/qh2p8r013lpuovs/mod-minelittlepony-1.10.2.1-mc1.10.2.litemod?dl=0

**Comment by killjoy1221** [comment]
Ok, so it works. I'll release now.

**Comment by ekevoo** [comment]
Thank you! <3

**Comment by nightfire68** [comment]
Same issue, I tried using the HD skin manager, but it is not working for me

**Comment by nightfire68** [comment]
![2017-03-17_22-03-03](https://cloud.githubusercontent.com/assets/26495625/24068144/acdf72b4-0b5d-11e7-9941-18fbf1c90666.png)

**Comment by killjoy1221** [comment]
@nightfire68 That's a different issue.
