### ISSUE TITLE
[1.12.2] Crash on loading/enter a world or joining server

### ISSUE THREAD

**Issue by DintyGadget** [MineLittlePony/MineLittlePony#111]
Forge 1.12.2-14.23.5.2824 (last ver)
Liteloader 1.12.2-00-SNAPSHOT (last ver)

[crash-2019-04-03_16.47.23-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3037491/crash-2019-04-03_16.47.23-client.txt)

i use modify launcher by new-Sashok724 (https://github.com/new-sashok724/Launcher)
on the older version of forge, everything worked stably and did not cause a crash. I can not upgrade to an older version, since some mods use almost the last build forge.

**Comment by Sollace** [comment]
MineLP hasn't been initialised, which means the litemod that hosts it didn't receive any events. Since you're using a non-standard launcher, I'd defer your problem to them.

It seems "Modify" Launcher is not loading liteloader the way it's supposed to be.
