### ISSUE TITLE
.jar file doesn't show up in mod list

### ISSUE THREAD

**Issue by RanosFox** [MineLittlePony/MineLittlePony#112]
I tried to use the .jar file by placing it in the mod folder, it doesn't show up or do anything. Am I using it wrong?

The reason I downloaded the .jar file is because liteloader can't be used with Project Ozone 3 mod pack due to it conflicting with one of it's mods. The game doesn't crash with this mod.

**Comment by killjoy1221** [comment]
The mod requires liteloader. Do not use the jar, it's not there for you to play with.

**Comment by RanosFox** [comment]
I see. Sadly, liteloader bugs out and crashes the game with Project Ozone 3. This is a quote from the creator of the conflicting mod: "LiteLoader is known to be broken with registry replacements (which apotheosis uses heavily)."

**Comment by Sollace** [comment]
Liteloader being "broken with registry replacements" seems very strange to me, considering I'be used it together with Unicopia in a dev environment and I'm doing exactly that.

Liteloader _does_ have a component that removes all the final modifiers from Blocks and Items fields, as well as a utility method that allows mods to do replacents through there. 

It's entirely possible that what Liteloader is doing has the side-effect of breaking forge's annotation-based carp. Either way, I suggest that any mod who tries to do registry replacements should also manually update those fields when they do to prevent awkward crashes from occuring, whether with or without liteloader.
