### ISSUE TITLE
Seapony race doesn't work

### ISSUE THREAD

**Issue by keupoz** [MineLittlePony/MineLittlePony#115]
The race works with issues in skin preview but in the game it doesn't work at all

![Screenshot from 2019-05-11 11-47-03](https://user-images.githubusercontent.com/39980087/57565167-aa641680-73e2-11e9-861f-2ac1a32e52ae.png)

![Screenshot from 2019-05-11 11-47-11](https://user-images.githubusercontent.com/39980087/57565168-b94ac900-73e2-11e9-8650-e8d78d2521e6.png)

Settings
![Screenshot from 2019-05-11 11-47-15](https://user-images.githubusercontent.com/39980087/57565170-c10a6d80-73e2-11e9-9692-948d1450c15c.png)

**Comment by keupoz** [comment]
The skin I used: https://github.com/MineLittlePony/MineLittlePony/blob/master/src/main/resources/assets/minelittlepony/textures/entity/seapony.png

**Comment by Sollace** [comment]
You only appear as a seapony when in the water.

**Comment by keupoz** [comment]
So you mean people have to design their skins so it doesn't look weird on land?

**Comment by Sollace** [comment]
Yes.

**Comment by keupoz** [comment]
Okay :I
