### ISSUE TITLE
[3.3 pre] Pegasi are missing a wing when using legacy 64x32 skins

### ISSUE THREAD

**Issue by BytewaveMLP** [MineLittlePony/MineLittlePony#116]
Didn't know if this was known internally or not, but I discovered that pegasi are missing a wing while messing around with the in-progress code and now the current pre-release. I'm unable to get my current skin if it's relevant, as I believe the file is lost to time, but my Minecraft username is `Bytewave` should it be useful in looking up the skin yourself.

![An image of a pegasus missing its left wing](https://user-images.githubusercontent.com/5623770/59553752-28c25400-8f5f-11e9-93c2-33d919014495.png)

**Minecraft version:** 1.14.2
**Fabric Loader version:** fabric-loader-0.4.8+build.154-1.14.2+build.2
**Fabric API version:** fabric-api-0.3.0+build.185
**MineLP version:** 3.3-pre

**Comment by Sollace** [comment]
You're using an old (legacy) skin with a 32x64 file dimensions. These aren't properly supported in this version because the mod needs to convert them internally to insert the other wing.

**Comment by Sollace** [comment]
If you enter the skins gui can you switch skin servers to whichever you're using and use the button to download your old skin?

**Comment by BytewaveMLP** [comment]
Ah, makes sense. I've had this around for a while, hadn't really messed with MineLP since then—guess I should get around to recreating/updating this old one.

And, huh. I wasn't actually aware you could switch skin servers. Neat! :p

The skin file, for reference:
![bytewave_pony_skin](https://user-images.githubusercontent.com/5623770/59553820-73909b80-8f60-11e9-8f21-2167255ecc27.png)

**Comment by Sollace** [comment]
^^

I'm not actually sure how many people know about the switch/download buttons as they were added late in 1.12.

And there you go, no longer lost to time!

**Comment by killjoy1221** [comment]
2f38419bc2350ccfbeab1a811b2b40912476ad40
e3fac2476cec051a4c206f877585ff505940921b
