### ISSUE TITLE
Area specific crash, possibly related to zombie villagers.

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#120]
Not entirely sure what's doing it, but looking through the logs I found:

[07:12:19] [main/WARN]: Villager texture `minelittlepony:textures/entity/zombie_villager/zombie_pony/taiga/armorer.png` was not found.
[07:12:19] [main/FATAL]: Unreported exception thrown!

so I assume it's the villager doing it.

Happens in the snapshots: [crash-2019-07-10_07.01.33-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3377383/crash-2019-07-10_07.01.33-client.txt)

And in pre3: [crash-2019-07-10_07.12.20-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3377389/crash-2019-07-10_07.12.20-client.txt)

[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/3377382/latest.log)

**Comment by killjoy1221** [comment]
This one seems a bit confusing. It looks like this line is possibly causing a recursive loop. We'll have to look into it later. I probably just need to rewrite that class (it has some missing features I'm concerned about).

https://github.com/MineLittlePony/MineLittlePony/blob/master/src/main/java/com/minelittlepony/client/render/entities/VillagerProfessionTextureCache.java#L78

**Comment by Sollace** [comment]
@killjoy1221 I haven't looked at the crash log, but I'm doubtful that's the cause. The exit condition is when it's called with the plains biome. If any of the other biome textures are missing, it's supposed to fall back to using the one for plains, and fail with the nitwit texture if that isn't there.

**Comment by Sollace** [comment]
Bleh. I can't use `getOrDefault` like that, it seems.
