### ISSUE TITLE
New 1.14 crouching mechanics causes player model to sink into ground

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#122]
Crouching was changed in 1.14 to affect player hitboxes, giving players the ability to crouch into 1.5 block tall spaces which forces the player into the sneak animation even if shift is released and forcing players into the swim animation when entering a 1 block tall space.

Standing normally: ![2019-07-11_05 54 02](https://user-images.githubusercontent.com/5730335/61046968-0bd54100-a3a4-11e9-8552-e6acace82650.png)

Sunk into ground slightly when in 1.5 block space, sneaking animation not applied : ![2019-07-11_05 53 52](https://user-images.githubusercontent.com/5730335/61047037-24ddf200-a3a4-11e9-88c7-304e48a911e7.png)

In 1 block tall spaces the swimming animation is applied, but the model is sunk into the ground: 
![2019-07-11_05 51 12](https://user-images.githubusercontent.com/5730335/61047141-61a9e900-a3a4-11e9-9ca9-2d26c67a96b9.png)

**Comment by killjoy1221** [comment]
It may be a good idea to rework the animation for sneaking. Any suggestions are appreciated.

**Comment by Sollace** [comment]
The first I know about. It was a bug turned feature, since visually the crouching animation looked weird when standing in a 1.5 space.

Crawling animation I also know about. It's a vertical translation issue I need to figure out, as it's going to be different for every model size too.

**Comment by Sollace** [comment]
https://github.com/MineLittlePony/MineLittlePony/commit/b1f7cda8cc5840f9200c8b3c7331ce9f233dcaaf
