### ISSUE TITLE
[pre4] Fillycam causes issues with bows and liquid placement.

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#123]
Bows are inconsistent as to where they shoot, but using a bucket on the side of a block consistently places the liquid one block above the selected block. 

Seems like a conflict between where the viewpoint is shown vs where it's supposed to be on a vanilla client. Happens in both multiplayer and SP. Tested as a standard height pone.

![waterbucket](https://user-images.githubusercontent.com/5730335/61183997-dcc20800-a60d-11e9-8e16-0c252610f423.gif)

Picking up liquid also has some desync issues. 
![waterbucket2](https://user-images.githubusercontent.com/5730335/61184060-a2a53600-a60e-11e9-89c1-7c587a3c2ab5.gif)

![bow](https://user-images.githubusercontent.com/5730335/61184096-442c8780-a60f-11e9-9699-f4be8f543c94.gif)

Tested in pre4, tried testing in source but got this crash: java.lang.NoSuchFieldException: MAINHAND [crash-2019-07-14_07.48.52-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3389880/crash-2019-07-14_07.48.52-client.txt)

I've also experienced the issues with buckets in pre3, not sure if it goes further back because I hadn't used the fillycam option before then.

**Comment by Sollace** [comment]
Pre-4 adds a fix for filly cam and bucket placement that adjusts the player's camera angle to align with what they're looking at. There shouldn't be any more major assignment issues save for a few small instances.

**Comment by derram** [comment]
All of these tests were done in pre4, just noting that I had experienced the issue with buckets in pre3 a well.

**Comment by Sollace** [comment]
Alright. Well I'll do some more testing.

There are some things I know that might cause it, but overall I've been playing with the foal model and not had any other problems.

The bows as well, there's a threshold for angles that it doesn't alter to avoid interfering with those things, though it's between allowing bows to work and buckets to not work. Might just disable it entirely when the player isn't actually looking at a block.

**Comment by derram** [comment]
@Sollace you want me to post issues I'm having when I build the jar from source?

That MAINHAND crash I referenced in this issue disappeared yesterday but seems to be back today.

[crash-2019-07-16_11.55.56-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3398227/crash-2019-07-16_11.55.56-client.txt)

**Comment by Sollace** [comment]
@derram Rather make a new issue for new bugs. I think I know what that MAINHAND error is. For now you may have to stick to playing it in a deobfuscated game until I can push a fix for that.
