### ISSUE TITLE
crashing in 1.14.4

### ISSUE THREAD

**Issue by EchoBounce** [MineLittlePony/MineLittlePony#124]
here is the crash report. i dont understand it, but crashes in jungle/desert biome
[crash-2019-07-24_00.28.51-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3425536/crash-2019-07-24_00.28.51-client.txt)

**Comment by Sollace** [comment]
That's a bug I fixed a few days ago relatibg to ponies having only one wing. The release must not have the right version of Kirin.

I'll do another update later to correct it.

**Comment by EchoBounce** [comment]
will it be a whole new release, or just a change to the current latest download?

**Comment by killjoy1221** [comment]
No need to update anything, just install this.
https://github.com/MineLittlePony/Kirin/releases/tag/1.4.2

**Comment by EchoBounce** [comment]
thank you so much ^^
