### ISSUE TITLE
Resource pack armor not working.

### ISSUE THREAD

**Issue by Powerless001** [MineLittlePony/MineLittlePony#125]
I can't seem to make the textures for armor work, no matter what, the armor just keeps using the default texture. Retexturing the mobs and such works, just not the armor.

**Comment by Venaf** [comment]
![image](https://user-images.githubusercontent.com/2046512/61844851-98810400-ae66-11e9-9118-2d2d6cc574c1.png)
You need to follow that naming and directory structure.

**Comment by ModernSilver** [comment]
@Powerless001 we'd love it if you could provide more details about the issue. What template are you following? Where are the files located? What are the files' names? Could you provide the files?

@Venaf keep in mind that directory only works for vanilla. For all we know they're trying to patch armor files for a another mod. In that case, the files would go where the mod keeps it's armor files, usually in `<modname>\textures\models\armor`

**Comment by Powerless001** [comment]
Thank you Venaf. You have solved it!
