### ISSUE TITLE
Drown heads are askew while swimming

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#127]
[1.14.4-3.3-pre6]

![2019-08-04_09 00 28](https://user-images.githubusercontent.com/5730335/62424738-986bda00-b698-11e9-976a-6263ae93084a.png)

![2019-08-04_09 07 30](https://user-images.githubusercontent.com/5730335/62424740-a28dd880-b698-11e9-84ca-95a8241e04a5.png)

It may only happen when the Drown is targeting a player bu they also start the swimming animation as soon as they target a player, so it's hard to say which is which.

![2019-08-04_09 24 14](https://user-images.githubusercontent.com/5730335/62424828-f9e07880-b699-11e9-9ccb-65d0d398a427.png)

![2019-08-04_09 24 34](https://user-images.githubusercontent.com/5730335/62424840-21374580-b69a-11e9-97c4-35d8972f95f4.png)

**Comment by Sollace** [comment]
Oh what on earth.

They're rotated 90deg

**Comment by Sollace** [comment]
https://github.com/MineLittlePony/MineLittlePony/commit/5066c7ad6482263c685cf9b54968f19372da6b93
