### ISSUE TITLE
[1.12.2] Issue with armors still presents on modded client

### ISSUE THREAD

**Issue by hectorskypl** [MineLittlePony/MineLittlePony#128]
Hi there,

The issue related to armors on modded clients are still present.

The easiest way to reproduce it, is just install Thermal Foundation mod and just equip the Bronze or another armor. And you just see this...
![2019-08-08_17 25 09](https://user-images.githubusercontent.com/5221712/62715955-bcfde400-ba01-11e9-9b8c-d72f9a7df837.png)
![2019-08-08_17 25 41](https://user-images.githubusercontent.com/5221712/62715956-bcfde400-ba01-11e9-8bd4-ac3cbe500e58.png)

It's something related to JIT texture conversion.
I hope this can be easily fixed.

**Comment by Sollace** [comment]
Can you provide a link to the mod so I can see what their armour textures are formatted as?


In general you need a resourcepack to add pony-compatible armour otherwise it will try to use the existing textures which are unlikely to fit perfectly.

**Comment by hectorskypl** [comment]
Hi there,

There is a link for ya https://www.curseforge.com/minecraft/mc-mods/thermal-foundation/download/2715788

**Comment by Sollace** [comment]
I have half a mind to say I'm not going to support bugs submitted for old versions unless they also affect 1.14 and can be backported.

**Comment by Sollace** [comment]
Fixed in 1.14. It's a complex change that won't be ported back to 1.12, though. https://github.com/MineLittlePony/MineLittlePony/commit/aff5920b0e003c1b4df643485f000713c28aa070
