### ISSUE TITLE
[1.12.2] Mixin Issues when running with Forge

### ISSUE THREAD

**Issue by Superplay64** [MineLittlePony/MineLittlePony#129]
So me and my friend have been putting together a modpack to do a co-op world, however Mine Little Pony causes an issue that prevents the game from starting.  After looking at the logs, it seems it is coming somewhere from within the hdskins portion under the "Mixin" output.  I'm entirely sure what exactly is causing the issue, but removing Mine Little Pony _does_ allow the game to start up without any issues.

Here are the regular and debug logs for review:
[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/3498307/latest.log)
[debug.log](https://github.com/MineLittlePony/MineLittlePony/files/3498308/debug.log)

**Comment by Sollace** [comment]
Try removing FoamFix and JustEnoughIds and see if the game loads without them.

The error looks like something else has already changed the main menu, making it incompatible with the mixins we use for HDSkins.

**Comment by Superplay64** [comment]
I removed both of those and ended up receiving this.  (I had disabled a bunch of mods on my first set of tests, and wasn't able to resolve the issue.  JustEnoughIDs had been one of them.)

[debug.log](https://github.com/MineLittlePony/MineLittlePony/files/3498494/debug.log)
[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/3498495/latest.log)

**Comment by Sollace** [comment]
I think there are still some incompatibilities between your mods. I'd just remove everything except Forge, Liteloader, and MineLittlePony and just slowly add things back to see where the error starts.

Phosphor needs a newer version of Mixin, which I think one of the mods you remove are adding, but when it adds it you kind of end up with mixins running twice (?) or something else. Not sure if it's something I can fix.

**Comment by Superplay64** [comment]
I'll have to do extensive testing at a later date.  Thank you for trying to help though.

**Comment by Superplay64** [comment]
Did some testing this morning.

The culprit mod seems to be _RandomPatches_.  Interestingly, I was actually able to allow Mine Little Pony to run along side this mod by disabling everything in RP's config file except for the login timeout extender for multiplayer connections.  At the moment, I haven't tested to find the exact feature that causes the issue when enabled.

**Comment by Sollace** [comment]
Ok, interesting! Do you have a link to RP so I can check it out? OwO

**Comment by Superplay64** [comment]
I totally forgot to reply to this!

[Here's the CurseForge page for _RandomPatches_](https://www.curseforge.com/minecraft/mc-mods/randompatches)
And
[Here's the GitHub for it.](https://github.com/TheRandomLabs/RandomPatches)

**Comment by Sollace** [comment]
Looks like RandomPatches is using ASM transformers. Unfortunately I don't think there's anything we can do to be more compatible with that.
