### ISSUE TITLE
RenderPlayer crash

### ISSUE THREAD

**Issue by CaptainKyros** [MineLittlePony/MineLittlePony#13]
[crash-2016-06-24_11.32.15-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/364537/crash-2016-06-24_11.32.15-client.txt)

**Comment by killjoy1221** [comment]
You need to install your graphics drivers. This is also unrelated to minelp. This crash would have appened in vanilla.

**Comment by CaptainKyros** [comment]
weird, for some reason it works fine w/o forge but when using forge it crashes

**Comment by killjoy1221** [comment]
Try what is here. https://bugs.mojang.com/browse/MC-33592

If that doesn't work, it's suggested to downgrade to [java 8u51](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u51-oth-JPR)

**Comment by killjoy1221** [comment]
This may be of use, too. https://github.com/LWJGL/lwjgl/issues/119

**Comment by CaptainKyros** [comment]
i updated my graphics driver but still had the problem

**Comment by CaptainKyros** [comment]
with Mine Little Pony
