### ISSUE TITLE
A few enhancement requests.

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#130]
I don't want to spam up the issue tracker with [enhancement] posts, so I figured I toss a few into a single post. If you like I can delete it and post them separately.

1. Ponified armor stands

2. The ability to apply a custom skin to a name tagged mob much the same way as we can apply a specific skin to certain players client side.

3. Sleeping in a bed automatically toggles third person view. 

4. Switch the skele pone mobs to a nub tail instead of a full tail. 

5. Raise the view for full size pones when riding a boat with filly cam enabled.

**Comment by Sollace** [comment]
1) we don't have any intention of adding ponified stands just yet. This has some implications for map makers.
2) That's a feature specific to HDSkins. I don't think we're going to include it with MineLp any time soon as name tags are already involved with certain unnamed easter eggs.

The other three can probably be achieved.

**Comment by killjoy1221** [comment]
3. Seems a bit out of scope. Feel free to install another mod that does that.
4. You could do that with a resource pack. If not, let us know.
5. That's valid.

**Comment by derram** [comment]
Should I post a request for 2 over on the hdskins tracker?

And 3 is more of a fix for the jumbled mess of geometry we see when sleeping in a bed. It's a lot like how beds worked when they were first added in vanilla, before the view was moved to avoid showing the inside of the player's head. I figured switching to the third person camera would be the easiest fix, but something should be done for it.

**Comment by Sollace** [comment]
I agree on 3. Though I don't know if forcing the player into 3rd person mode is the best way of doing it.

Last time I tried to deal with this it was by hiding the pony's head.

**Comment by Sollace** [comment]
Also 2 doesn't really fit here or there. HD Skins specifically only works with player skins, and skins for other mobs specifically won't be possible without some major breaking of scope.

It sounds more like something you could achieve with another mod, or the Random Mobs feature resourcepack features Optifine adds.

**Comment by derram** [comment]
Seems MineLP is overriding the custom skin when using optifine's random entities option.

I was able to set a custom skin for named mobs without MineLP installed, though. 

I tried naming the texture the default name and even with a _pony added, but the mod just shows the default MineLP texture for the mob. A changeling, in this case.

All done with optifabric installed, so I don't think the problem is there.

**Comment by Sollace** [comment]
You probably have to write your rando mobs stuff to specifically apply to the minelp textures. They don't work the same way as armour textures.

**Comment by derram** [comment]
It's a complete texture replacement.

![2019-08-22_23 54 56](https://user-images.githubusercontent.com/5730335/63569812-82876180-c540-11e9-889b-de9d9e32ea43.png)

I edited a MineLP texture as well, but it doesn't get loaded and only the default changeling is shown.

**Comment by derram** [comment]
Did a lil more testing and disabling the villager ponification causes the custom skin to show up on the name tagged mobs even with MineLP installed.

![2019-08-23_06 48 24](https://user-images.githubusercontent.com/5730335/63590711-43720400-c572-11e9-80e8-92ce6d665f6a.png)

This seems like an incompatibility between the mods, should I make a new issue specifically for it?

**Comment by Sollace** [comment]
How are you setting up your resourcepacks?

To change the skins MineLP uses you have to replace `assets/minelittlepony/textures/entity/illager/evoker_pony.png` _not_ `assets/minecraft/textures/entity/illager/evoker.png`.

**Comment by derram** [comment]
Optifine looks for the alt skins in `/assets/minecraft/optifine/random/entity/illager/`

Tried adding them to the MineLP style path, but no go there either.

[afmobs_resource_pack.zip](https://github.com/MineLittlePony/MineLittlePony/files/3534774/afmobs_resource_pack.zip)
