### ISSUE TITLE
Pillager ponification is handled under Villagers instead of Illagers in the f9 menu

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#131]

**Comment by Sollace** [comment]
Pillegers and Illagers are in the same family as Villagers so it's #notabug .

**Comment by derram** [comment]
The f9 menu has a separate toggle for illagers and villagers, tho.

**Comment by Sollace** [comment]
Ah. Well regardless, I specifically decided to lump pillagers in with their friendly counterparts. I suppose we can split them up for consistency, though I have no clue who would want one without the other.
