### ISSUE TITLE
Crash on 1.15

### ISSUE THREAD

**Issue by Siphalor** [MineLittlePony/MineLittlePony#138]
Just wanted to give it a try but got this crash on startup: https://paste.ee/p/VFSwX

How to reproduce:
* Create a 1.15 minecraft instance
* Install MLP and Fabric API
* Start it and enjoy the crash :)

**Comment by Sollace** [comment]
Oh, dangit. Something in Mson broke.

I'll look at trying to fix it tomorrow.

**Comment by killjoy1221** [comment]
Looks like it's scheduling a task that reschedules itself again to be run
right away. Ah, the wonders of recursion.

**Comment by Sollace** [comment]
Nah, that's not it. It's an issue with the method handles that get constructed when that class is loaded.

**Comment by killjoy1221** [comment]
It's all these intermediate class names that has me confused. It's just as
bad as obf.

**Comment by Sollace** [comment]
Srg would be the same, and there is hardly any intermediate names in that stacktrace. Important piece is:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.minelittlepony.mson.api.model.BoxBuilder
	at com.minelittlepony.mson.impl.model.JsonBox.export(JsonBox.java:44) ~[68f3c864-1b12-4deb-b7cc-f215289013e3.jar:?]
	at com.minelittlepony.mson.impl.model.JsonBox.export(JsonBox.java:20) ~[68f3c864-1b12-4deb-b7cc-f215289013e3.jar:?]
	at com.minelittlepony.mson.api.json.JsonComponent.tryExport(JsonComponent.java:25) ~[68f3c864-1b12-4deb-b7cc-f215289013e3.jar:?]
	at com.minelittlepony.mson.impl.model.JsonCuboid.lambda$export$6(JsonCuboid.java:112) ~[68f3c864-1b12-4deb-b7cc-f215289013e3.jar:?]```

**Comment by derram** [comment]
I'm still getting this crash in 4.0.1 

> The game crashed whilst rendering overlay
> Error: java.lang.NoClassDefFoundError: Could not initialize class com.minelittlepony.mson.api.model.BoxBuilder

**Comment by Sollace** [comment]
@derram Do you have anything else installed?

**Comment by derram** [comment]
Just HDskins.

![Selection_029](https://user-images.githubusercontent.com/5730335/70619184-5df8e780-1c0c-11ea-886e-6edc5328e152.png)

**Comment by Sollace** [comment]
@derram The issue is with Mson, so please clear out your entire mods folder except for fabric-api (remove the folders too) and test with this jar.

It will produce a crash. Just send back the log file.

[Mson-1.1.5-1.15-SNAPSHOT.zip](https://github.com/MineLittlePony/MineLittlePony/files/3950178/Mson-1.1.5-1.15-SNAPSHOT.zip)

**Comment by Sollace** [comment]
(the jar is in the zip because github wouldn't let me upload it as it was)

**Comment by derram** [comment]
[crash-2019-12-11_06.11.22-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3950223/crash-2019-12-11_06.11.22-client.txt)

**Comment by Sollace** [comment]
Okay... So it's nothing to do with my code.

This some kind of configuration error.

**Comment by Sollace** [comment]
@derram You can try removing the launcher profile and re-running the fabric installer.

Here are the configurations I used to set mine up.
![image](https://user-images.githubusercontent.com/6429283/70620736-b0440380-1c20-11ea-8e1c-faee7b1a18b7.png)

**Comment by Sollace** [comment]
@derram Can you try again with this one, please?

[Mson-1.1.4b-1.15-SNAPSHOT.zip](https://github.com/MineLittlePony/MineLittlePony/files/3950367/Mson-1.1.4b-1.15-SNAPSHOT.zip)

**Comment by derram** [comment]
[crash-2019-12-11_07.19.48-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3950508/crash-2019-12-11_07.19.48-client.txt)

Also tested it out on my laptop and got the same crash, so I doubt it's something in my install folder.

Currently installing minecraft on the laptop's Windows install to test if this is something specific to Linux.

**Comment by Sollace** [comment]
@derram That's fine, it's a test build. Everything looks good, thanks!

You can install the 4.0.2 version of MineLP.

**Comment by derram** [comment]
Crash is gone, thanks again!
