### ISSUE TITLE
recurring RenderPlayer crash 

### ISSUE THREAD

**Issue by CaptainKyros** [MineLittlePony/MineLittlePony#14]
i still keep getting the crash  #13  and i updated my graphics driver to the latest version
(i am on Win10 32-bit with a x64 processor btw) and it only seems to happen when i use liteloader AND forge

**Comment by killjoy1221** [comment]
Oddly when I tried to reproduce this (installing forge), I got a completely different crash. I'm thinking it's a forge bug. I'll have to try again when MinecraftForge/MinecraftForge#3055 is pulled.

**Comment by stricq** [comment]
I'm seeing the same crash with Forge 2014.

**Comment by killjoy1221** [comment]
I might be able to work around this by providing a separate litemod just for forge. This issue is probably with forge's runtime deobfuscator, so providing a pre-deobfuscated mod should prevent this.

**Comment by CaptainKyros** [comment]
how do you compile it without a gradlew.bat?
sorry I'm new at liteloader

**Comment by killjoy1221** [comment]
You'll need to either add gradle to your path or add the wrapper yourself. As soon as #11 gets confirmed as fixed, I'm going to release it anyway.

**Comment by killjoy1221** [comment]
does it still crash using [1.10.2.1](https://github.com/MineLittlePony/MineLittlePony/releases/tag/1.10.2.1)?

**Comment by stricq** [comment]
Verified 1.10.2.1-forge is working with Forge on local and server worlds. Thanks!

**Comment by killjoy1221** [comment]
I'll keep this open until the better solution is implemented forge-side.

**Comment by killjoy1221** [comment]
MinecraftForge/MinecraftForge@d7245c5ffefddb5431cf9d9394ec621ec1b22a4f

Try the normal download with forge 2020

**Comment by webrsb** [comment]
Single player mode is working but does not on mutiplayer.
http://codepad.org/B6cCjsRO
