### ISSUE TITLE
Player Model issue in modpack with MC version 1.12.2; Mine Little Pony Versions 3.2.6 &3.2.7

### ISSUE THREAD

**Issue by The-Imagemaker** [MineLittlePony/MineLittlePony#141]
Below are some screen shots of what happened with the player model.
<details>
  <summary>Screen Shots</summary>

![2020-01-02_11 42 31](https://user-images.githubusercontent.com/23262285/71679206-06562380-2d55-11ea-9786-f2af95ffae9b.png)
![2020-01-02_11 42 43](https://user-images.githubusercontent.com/23262285/71679208-06eeba00-2d55-11ea-9ac9-adc185835e03.png)

</details>

I am uncertain if this issue is from Mine Little Pony (MLP), or from another mod, but from what I can tell, MLP is the only mod I have that effects the player model. I was in creative mode and was flying downward, and the player model broke as in the images above when I collided with the ground. 

It did not cause an issue that closed minecraft. I have included the log file from the date that this happened. The issue persists between multiple instances of Minecraft.

I am using Light Loader for 1.12.2 installed onto Forge version 14.23.5.2847 as the mod loader.

Log File:
[2020-01-01-4.log](https://github.com/MineLittlePony/MineLittlePony/files/4016494/2020-01-01-4.log)

**Comment by Sollace** [comment]
Only forge can somehow have a log file of almost 2MB.

I've not really seen the model break that badly. There are so many exceptions and errors I can't really find any issue specific to us, and it seems like something is breaking transformations somewhere.

Try loading in a new world without any other mods. CustomNPCs does stuff with the pony models, but it could well be any number of things rendering at the same time which causes this breakage.

**Comment by killjoy1221** [comment]
I would try again without optifine. See if that helps.

**Comment by Sollace** [comment]
Oh yes! Totally missed that in the logs.

**Comment by The-Imagemaker** [comment]
It was optifine. Guess I'll have to switch to use Techguns instead of Modern Warfare for weapons. Thank you for your help.
