### ISSUE TITLE
Clothing layer is shaped encorrectly

### ISSUE THREAD

**Issue by Game-Log** [MineLittlePony/MineLittlePony#144]
As seen on the left side of the screen, the outer/clothing layer on 1.8+ skins seem to copy the layer onto the neck position. (Bug occurred on Minecraft version 1.15.1)

![Screenshot (3)](https://user-images.githubusercontent.com/59855439/72307644-f8ec4380-3648-11ea-9060-56e17acf3d76.png)

**Comment by Sollace** [comment]
I don't see what the issue is. Your skin looks correct on the right there.

**Comment by Game-Log** [comment]
> I don't see what the issue is. Your skin looks correct on the right there.

While, yes, it looks fine on the right side, look carefully to the skin on the left. That is the skin that I plan to use; having moved the clothes on the skin to the secondary layer. As you can see on the left side of the image, it looks as if the secondary layer is put onto the neck.

**Comment by Sollace** [comment]
> > I don't see what the issue is. Your skin looks correct on the right there.
> 
> While, yes, it looks fine on the right side, look carefully to the skin on the left. That is the skin that I plan to use; having moved the clothes on the skin to the secondary layer. As you can see on the left side of the image, it looks as if the secondary layer is put onto the neck.

Okay. Send your skin then so I can have a look.

**Comment by Game-Log** [comment]
> > > I don't see what the issue is. Your skin looks correct on the right there.
> > 
> > 
> > While, yes, it looks fine on the right side, look carefully to the skin on the left. That is the skin that I plan to use; having moved the clothes on the skin to the secondary layer. As you can see on the left side of the image, it looks as if the secondary layer is put onto the neck.
> 
> Okay. Send your skin then so I can have a look.

Ok, here is the skin.

![Skin](https://user-images.githubusercontent.com/59855439/72474981-f8be8600-37b7-11ea-9608-7108ec569ed8.png)
