### ISSUE TITLE
I Cant Upload my "skin" i need help

### ISSUE THREAD

**Issue by MrMonster61** [MineLittlePony/MineLittlePony#149]
Pls its like this
                                                                  Uploading skin failed:
    sun.security.provider.certpath.suncertpathbuilderexception:unable to find valid certification path to    requested target

**Comment by Sollace** [comment]
Refer to the installation instructions for HD Skins here: https://github.com/MineLittlePony/HDSkins/releases/tag/v6.1.1-mc1.15.2
