### ISSUE TITLE
sun.security.provider.certpath.suncertpathbuilderexception:unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by MrMonster61** [MineLittlePony/MineLittlePony#150]
I Receved Your Comment on how i shoud fix my problem but it didnt help

**Comment by Sollace** [comment]
2. The skin server uses Let's Encrypt for HTTPS certificates. Unfortunately, the version of Java Mojang ships with Minecraft does not support this, so you will need to install [LetsEncryptCraft](https://github.com/killjoy1221/LetsEncryptCraft/releases/latest) LetsEncryptCraft</a> to upload your skins.
