### ISSUE TITLE
Please make the mod for Forge

### ISSUE THREAD

**Issue by ZuranaSuki** [MineLittlePony/MineLittlePony#153]
As the title suggests it would be nice if the latest versions could be on Forge

**Comment by killjoy1221** [comment]
I would love to, but I'm limited by [Layer 8](https://en.wikipedia.org/wiki/Layer_8)

**Comment by ModernSilver** [comment]
**Disclaimer**: I'm not a MineLP Dev, so feel free to take this reply with a grain of salt.

Well, this got a good laugh out of me. XD

I'm sorry to say that I don't think the mod will be ported over to Forge in the foreseeable future, mainly due to differing opinions and I'm sure some coding issues. I'm sure the mod could be ported over, but it could require an entire rewrite of the mod.

Assuming the license supports it, someone could fork it and try to port to Forge, but that'd be impractical. They'd need to mirror changes from the Fabric branch onto the Forge branch. It'd be better if Fabric/Forge devs could work out some compatibility, not sure when/if that would happen.

I'd love it if I could use MineLP with Forge mods in 1.14+ as well, but I'm afraid that's impossible for the foreseeable future.

**Comment by Sollace** [comment]
Forge is a highly opinionated framework with a lot of bloat, hard to understand, convoluted, and badly-designed APIs that it has aquired through several years of questionable practices. Their dev team gas a history of talking down to their userbase, treating devs like lesser humans, and acting entitled as they intentionally implement changes that put non-forge apis at a disadvantage.

They have a restrictive license on the MCP names that make it difficult to use, or improve for other projects. Many of the MCP names are also wrong or misleading, making it inifinitely more difficult to develop mods under their umbrella that don't end up misusing Mojang's methods of creating bugs.

Forge itself patches the game in ways that break or change features in vanilla, lovks out official APIs, and that at times makes it more difficult to do certain things with the game. Their approach of adding events for everything is also inefficient and are known to cause performance problems in the game.

They are slow to update and may take several months before they are ready for a new version of Minecragt whilst Fabric currently has had several stable releases for 1.16.

**Comment by killjoy1221** [comment]
Everything you just said is a lie.

**Comment by Sollace** [comment]
I have witnessed it with my own eyes.

**Comment by killjoy1221** [comment]
1. Large frameworks tend to attract bad programmers who don't follow established best practices.

2. MCP isn't a thing anymore, just the mappings are used. And the license only applies to redistribution. Lex, the owner, always denies any restrictions that don't cause binary incompatibilities. Actual names can be changed to whatever you like. If names are wrong, they can be fixed. 

3. While source patches is a "necessary evil", they don't break vanilla components. It's a requirement when submitting new patches to not break compatibility. Also note that anything provided by Mojang in obfuscated form cannot be considered API. 

4. Events are generated using ASM. It's actually quite fast when combined with Unsafe. Do you have benchmarks to support the performance issues?

5. Forge is updated same day for minor versions, often next day for major. Also note that 1.16 is not released yet. If you want snapshot mods, then go ahead with fabric.

**Comment by Sollace** [comment]
1. The bad code is part of the framework itself. They're filled with bad practices. I used to hate them as an end user, but having to work with Forge as a dev has only made.me despise them more.

**Comment by Sollace** [comment]
2. The MCP name still applies to the mappings. Their license doesn't allow you to change them outside of Forge's main repo, and no one is allowed to make alternative versions of it.

**Comment by Sollace** [comment]
3. Forge locks down the registries, and changes how block models work that make them more annoying to use than in vanilla. I have also seen, and made an issue, for how Forge breaks the item for snow layers.

**Comment by Sollace** [comment]
4. I'm not saying the ASM is slow. It's the fact that they have hundreds of thousands of these events, at generic locations, some of which run on ever frame. There are benchmarks. Just look online for server benchmarks, or just play the game with an average computer and look at the framerate.

**Comment by Sollace** [comment]
5. You clearly don't remember how long the wait for an update used to be. I particularly remember mods taking so long to update that Mojang had already released the next version of Minecraft in the meantime. How long after 1.13 came out did it take for forge to get an unstable release?

**Comment by killjoy1221** [comment]
1.13 doesn't count. The delay in that was because they wanted to do a complete rewrite of everything. It's better because of it.

**Comment by Sollace** [comment]
You can see the same delay to lesser extends on every Minecraft version before that. In fact, it's been slowly getting longer over the past 10 years as forge gets bigger.
