### ISSUE TITLE
How do i change skin?

### ISSUE THREAD

**Issue by ZuranaSuki** [MineLittlePony/MineLittlePony#154]
there is no gui for uploading pony skins and i cant figure it out

**Comment by killjoy1221** [comment]
HDSkins is now a separate download. You can get it from [here](https://github.com/MineLittlePony/HDSkins/releases/latest)

**Comment by ZuranaSuki** [comment]
ohhh ok thank you

**Comment by Gamedestroyer112** [comment]
Hey. I don’t have a computer to use this. Is there any way to port it to Minecraft PE? Or at least a Minecraft PE version that can be imported into MCPE Addons? Plz respond back via email at:
Elijahrussell@lhsvikes.net

I will only know it’s you if you’ve Put in the subject box:
MineLittlePony Chat.
