### ISSUE TITLE
Changelings right wing are upside down

### ISSUE THREAD

**Issue by Idze** [MineLittlePony/MineLittlePony#155]
The right wing on Changeling are the wrong way
![2020-02-27_23 19 50](https://user-images.githubusercontent.com/61480413/75492547-48e45700-59b8-11ea-80c5-470ec28dc9e5.png)

**Comment by ModernSilver** [comment]
That's a pretty good resource pack I'm seeing.

I'm assuming it's some kind of HD variant of Love & Tolerance?

**Comment by killjoy1221** [comment]
Idze is the maintainer of Lemons & Tolerance

**Comment by Sollace** [comment]
@Idze Please send the skin you're using. Pillagers are using changeling skins and they appear correctly in game.

**Comment by Idze** [comment]
sorry it tog so long but here is the skin https://imgur.com/AMYgtdC

**Comment by Sollace** [comment]
@Idze Your skin is wrong. The right wind is supposed to be a mirror of the left.
