### ISSUE TITLE
Ray Tracing

### ISSUE THREAD

**Issue by Trixielulamoon** [MineLittlePony/MineLittlePony#157]
I can't figure out how to just ask a question, so sorry if this is in the wrong spot.
With everypony changling over to Ray Tracing in minecraft. Does Mine Little Pony work with Ray Tracing or will it in the future? I want to switch over to Ray Tracing but I won't give up Mine Little Pony for it. If it's already compatible with Ray Tracing, how do I get it to work? I tried Optifine and Forge and that didn't work. Anyways, thanks for the great mod and keep up the great work.

**Comment by killjoy1221** [comment]
As far as I'm aware, it has worked with shaders (both SEUS and optifine) for as long as it's been a thing. I am unaware of any changes with fabric though. Does optifabric have shaders support?

**Comment by Sollace** [comment]
@killjoy1221 Optifabric is just the normal Optifine jar patched and remapped, so it does have shaders support, yes.

I tried it for a bit but my setup has never had great performance with shaders or Optifine.
