### ISSUE TITLE
Changeling and Reformed Changeling different

### ISSUE THREAD

**Issue by Idze** [MineLittlePony/MineLittlePony#158]
I was thinking  the trigger pixel for the not reformed Changeling and the Reformed Changeling could show different
#282b29 can have the wing showing all the time like in the show
and #caed5a only show the wing wen flying, swimming and crouching

**Comment by Sollace** [comment]
Do we have precedent for reformed changelings always showing their wings? I'm aware of Thorax, but he's much like Queen Cheesy, and other reformed changelings (Ocellus) don't seem to always have their wings open.

**Comment by Idze** [comment]
ad the moment both only show wing wen flying but the love eating one have there wing out al the time
![Mlp_changeling_by_matty4z-d5mbm1c](https://user-images.githubusercontent.com/61480413/76692563-ad5e1200-6658-11ea-8510-0377d2e513f5.png)

**Comment by Sollace** [comment]
Ah. I see.

If I change it now, I'm afraid I will break people's existing skins, though. They're kind of used to the current behaviour for now.

**Comment by Sollace** [comment]
Changeling models are kind of reserved for moose bois in the future anyway. In fact, anyone who can make resourcepacks is welcome to design one themselves, as that's been make accessible to do.

**Comment by Idze** [comment]
don't see how that is that big of a problem  it use to be that the wing were show al the time, this way you can have a choice if you want wing always showing or not  
![2](https://user-images.githubusercontent.com/61480413/76713126-cf21cc80-671e-11ea-8f37-0f144be83d0c.png)

**Comment by PolyacovYury** [comment]
I mean, there are regular pegasi who have different models for extended and folded wings. Why not use that system to make it so that only extended wings on reformed changelings have a model at all?
Also, those wings seem shifted too far back.

**Comment by Sollace** [comment]
>  those wings seem shifted too far back.
Changelings have two sets of wings. He seems to have only textured the secondary ones.

**Comment by Sollace** [comment]
@Idze Please send the skin you're using. Pillagers are using changeling skins and they appear correctly in game.

**Comment by Idze** [comment]
Sorry it to so long to post but here is the skin i used
![taiga](https://user-images.githubusercontent.com/61480413/96766834-f4289d00-13db-11eb-9413-b34ad577c40f.png)

and because you closet the flip wing issues i am just going to post this skin were you can see that the wing a flip on the right
![IdzebugRedGreen](https://user-images.githubusercontent.com/61480413/96767577-ffc89380-13dc-11eb-912f-4452ca1b5909.png)
![2020-10-21_20 35 01](https://user-images.githubusercontent.com/61480413/96767594-05be7480-13dd-11eb-9073-0dfc5c0d351d.png)
