### ISSUE TITLE
Crash using Mine Little Pony 4.0.6 using Fabric and Minecraft 1.15.2.

### ISSUE THREAD

**Issue by alxpettit** [MineLittlePony/MineLittlePony#159]
I was fighting a skeleton and it just crashed in the middle of the fight. See log [here](https://gist.github.com/alxpettit/b586f9695f33f5d66315fc0354acdf5d).

**Comment by alxpettit** [comment]
Happened again. This time, I was wandering through a cave. Didn't even see any other mobs: https://gist.github.com/alxpettit/cb1a44fb232e1049b983a509741cef6a

**Comment by PolyacovYury** [comment]
`[20:40:49] [Server thread/INFO]: ThreadedAnvilChunkStorage (OwO): All chunks are saved`

**Comment by Sollace** [comment]
That crash shouldn't actually happen. It's a vanilla bug that was patched in Mson a few versions ago. Let me check.

**Comment by Sollace** [comment]
@alxpettit You can try this version and see if it fixes the crash. https://github.com/MineLittlePony/Mson/releases/tag/b.1.1.10

**Comment by Sollace** [comment]
As I've had no feedback, I'm closing this as resolved.

**Comment by alxpettit** [comment]
@Sollace Sorry 'bout that.

It's kind of difficult to test since it's a random crash, but as of right now, I haven't experienced a crash since installing  the Mson update. So it's resolved... probably?

Probably.

**Comment by joeyjumper94** [comment]
still getting it
it seems to be when a pony is rendered when it has an arrow sticking out

**Comment by joeyjumper94** [comment]
[crash-2020-06-13_21.58.27-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/4775886/crash-2020-06-13_21.58.27-client.txt)

**Comment by Sollace** [comment]
If you're still getting the crash make sure you're running MineLittlePony 4.010 or higher. https://github.com/MineLittlePony/MineLittlePony/releases/tag/1.15.2-4.0.10

**Comment by PCelestia** [comment]
in general, if you haven’t, try updating to the latest version before you create an issue because it’s probably fixed already in the latest version
