### ISSUE TITLE
[FORGE] Unicorn skeleton glow not positioned correctly. 

### ISSUE THREAD

**Issue by agentguy12345** [MineLittlePony/MineLittlePony#16]
![screenshot from 2016-08-27 13-36-44](https://cloud.githubusercontent.com/assets/21277859/18027444/5bc869d6-6c5b-11e6-9c65-2ad3e21f2a90.png)

**[FORGE MIX-IN]** Unicorn skeleton glow not positioned correctly.

**Comment by agentguy12345** [comment]
This could happen for players too (and other mobs). I haven't tested.

**Comment by killjoy1221** [comment]
I could've sworn I fixed this. Oh well.

**Comment by killjoy1221** [comment]
Specifically 4f73a6067624196799c1600ad439921002ae0041

**Comment by agentguy12345** [comment]
Hope I helped by reporting the bug. :)

**Comment by agentguy12345** [comment]
Seems to work okay with resource pack that changes bow.
