### ISSUE TITLE
Side of nose is transparent in Steve-model ponies

### ISSUE THREAD

**Issue by Game-Log** [MineLittlePony/MineLittlePony#161]
![2020-03-29_21 26 03](https://user-images.githubusercontent.com/59855439/77868160-25efd180-7208-11ea-93db-cbc1679160fd.png)

While this bug was squashed in ponies with the Alex-Model, it seems as if it persists for those using the Steve-Model.

**Comment by Sollace** [comment]
Do you mean the stallion snout? Steve/Alex only affects the legs and I know for a fact _mare's_ snouts were fixed.

**Comment by Sollace** [comment]
Will be fixed in the next release.

**Comment by Game-Log** [comment]
> Do you mean the stallion snout? Steve/Alex only affects the legs and I know for a fact _mare's_ snouts were fixed.

Ah, yes; thats what i meant. Sorry for any confusion.

**Comment by Sollace** [comment]
@Game-Log Alright. Well no problem. I found the issue. You can download the fixed version from the releases tab.
