### ISSUE TITLE
GuiMainMenu was already transformed.

### ISSUE THREAD

**Issue by Kadanza** [MineLittlePony/MineLittlePony#163]
I use modpacks MC Eternal. I put liteloader mod and PonyMod to mods folder.
When i try to run I got error on loading. I use minecraft 1.12.2 

Critical problem: hdskins.mixin.json:MixinGuiMainMenu target net.minecraft.client.gui.GuiMainMenu was already transformed.

 org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hdskins.mixin.json:MixinGuiMainMenu target net.minecraft.client.gui.GuiMainMenu was already transformed.
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
> 	at java.lang.Class.forName(Unknown Source) [?:1.8.0_181]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> [16:10:29] [main/ERROR] [LaunchWrapper]: Unable to launch
> java.lang.ClassNotFoundException: net.minecraft.client.main.Main
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
> 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [hdskins.mixin.json:MixinGuiMainMenu] from phase [DEFAULT] in config [hdskins.mixin.json] FAILED during PREPARE
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 6 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hdskins.mixin.json:MixinGuiMainMenu target net.minecraft.client.gui.GuiMainMenu was already transformed.
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[bewitchment-1.12.2-0.0.21.10.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 6 more
> Exception in thread "main" [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [16:10:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sollace** [comment]
This is an incompatibility with one of your other mods.
