### ISSUE TITLE
1.16 or something for MC snapshot 20w21a

### ISSUE THREAD

**Issue by joeyjumper94** [MineLittlePony/MineLittlePony#164]
i was wondering where i can get something for the beta versions of 1.16
AKA play as ponies in the preview of the nether update

**Comment by Sollace** [comment]
@joeyjumper94 We don't release for snapshot versions, however you are welcome to try the snapshot builds from our maven. the latets version we have was for 20w20b, however I see no reason for it not to work in 20w21a as well so long as you also have the correct FabricAPI version.

https://repo.minelittlepony-mod.com/?prefix=maven/snapshot/com/minelittlepony/MineLittlePony/4.1-20w20b-SNAPSHOT/
and
https://repo.minelittlepony-mod.com/?prefix=maven/snapshot/com/minelittlepony/HDSkins/6.1.4-20w20b-SNAPSHOT/

**Comment by joeyjumper94** [comment]
all that i get from those links is a page that says
> Error: [object Object]

**Comment by Sollace** [comment]
@joeyjumper94 Are you on desktop? They work for me on desktop, but mobile browsers display that error still.

Otherwise i think @killjoy1221 knows more about it.

**Comment by killjoy1221** [comment]
Sometimes the file listing fails. Usually using http instead of https works.

**Comment by Brian151** [comment]
i was going to say the mod didn't even UPDATE for snapshots. but ofc, we do have those wonderful obfuscation mappings now [which makes me somewhat question the legitimacy/benefit of Mojang continuing to use an obfuscator] , but i still wouldn't expect keeping a mod up to date with snapshots to be terribly easy/feasible.

well, that's cool

**Comment by Sollace** [comment]
@Brian151 Not to mention Mojang releases their own mappings for the game (which are ARR). There are still advantages to keeping the obfuscations, though. i.e. The obfuscated jar is smaller than it would otherwise be.

**Comment by joeyjumper94** [comment]
i keep getting redirected to HTTPS, i am on a laptop, FireFox browser

**Comment by Brian151** [comment]
> 
> 
> @Brian151 Not to mention Mojang releases their own mappings for the game (which are ARR). There are still advantages to keeping the obfuscations, though. i.e. The obfuscated jar is smaller than it would otherwise be.

the officially released mappings are exactly to what i refer.

one one hand, this is true. but on the other hand, the argument can just be made to compile the game as a native app. done right, it can't possibly be smaller. There probably are better ways to make the jar smaller. In any case, all the extra files the launcher downloads [like language packs i KNOW i will never use] take considerably more space than the jar.

**Comment by Brian151** [comment]
oh, and i also get that error
Pale Moon [firefox with a little bit less of the BS] 28.9.3 64-bit

this appears in the error console:
Object { readyState: 0, getResponseHeader: getResponseHeader(), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(), overrideMimeType: overrideMimeType(), statusCode: statusCode(), abort: abort(), state: state(), always: always(), catch: catch(), 8 more… }

looks like an XMLHTTPRequest object, but unfortunately there's nothing to explain why the page is broken

**Comment by killjoy1221** [comment]
It might be because of certificate errors on amazon's side caused by my bucket name being a fqdn. In the meantime, use this url.

https://repo.minelittlepony-mod.com.s3.amazonaws.com/index.html

**Comment by Brian151** [comment]
well, it worked. got the good old "untrusted connection!" page though, which might scare-away some folks

**Comment by killjoy1221** [comment]
I'll work on making the url a single slug soon, though most people won't need to use it. In fact, since you added the certificate exception, the main url should work now.

**Comment by Andy-K-Sparklight** [comment]
Scare-away... It won't affect true MLP fans~

**Comment by Brian151** [comment]
> 
> 
> Scare-away... It won't affect true MLP fans~

as a developer and end-user of web browsers that enforce their security like the KGB or Guantanamo Bay, I can attest that you don't need the user to be scared-away, you just need the browser to decide even at its most lax security settings that the page/script is dangerous. short of making edits to the source code or even live-hacking the active process, adding specific extensions/plugins, you AREN'T ACCESSING THAT SITE/PAGE. and that text wall being said, cert error page is one of the security features you can't always bypass. i play a crappy/questionable chinese-made MMORPG and the most recent of SEVERAL issues i had was a cert error. this is something that needs to be addressed. your user might be smart, the browser doesn't care. modern security is inherently anti-user.

**Comment by killjoy1221** [comment]
I fixed up the ssl issues.

https://repo.minelittlepony-mod.com/maven/snapshot/com/minelittlepony/MineLittlePony/4.1-20w20b-SNAPSHOT/
https://repo.minelittlepony-mod.com/maven/snapshot/com/minelittlepony/HDSkins/6.1.4-20w20b-SNAPSHOT/

**Comment by killjoy1221** [comment]
This issue has gotten way off topic. Locking.
