### ISSUE TITLE
1.12 Seapony tail not rendering properly

### ISSUE THREAD

**Issue by Roboslime** [MineLittlePony/MineLittlePony#165]
The tails of seaponies are not properly rendering (the cube is too far inside the body). Also, the arms are screwy...
![Screwy Seapony](https://user-images.githubusercontent.com/36549179/83211512-4914ff80-a12b-11ea-8066-57bc4a92698c.png)
I Just made this wireframe to show the issue...black arms are the top layer arms

**Comment by Roboslime** [comment]
As a side note, would there be any possibility of changing the seapony mapping so the two forms are more compatible?

**Comment by Sollace** [comment]
Unfortunately not. The pony and seapony mappings are inherently incompatible and there's nothing we can do to make them both fit on the same texture file without some hackyness.

**Comment by Sollace** [comment]
This bug is not present on 1.13+ versions of the mod. We don't actively support 1.12, however if I ever get to making another ESR build I'll try to make this one of the fixes.

**Comment by Roboslime** [comment]
Sorry about forgetting the tags...
I get that 1.12 isn't supported, and I would have fixed it myself, but then i discovered that unlike the later versions, the models are stored in .class files rather than editable .json. To be honest, from the movement and such, it seems the pivoting of the tail is entirely correct, just that the one part needs to be shifted up slightly and moved backwards.


You're probably already aware of that, just wanted to mention it.

**Comment by Sollace** [comment]
That is actually correct. The positioning of that one cube is just shifted a little far forward in that version.

The legs layers not aligning is also know - it was just that they weren't being posed correctly in that version.

Both issues would have been fixed in post 1.13 versions.
