### ISSUE TITLE
Doesn't show up in liteloader side tab.

### ISSUE THREAD

**Issue by Aquaeyes** [MineLittlePony/MineLittlePony#17]
I've tried the latest and second latest versions inside the 1.10 folder and the mods folder, and neither show up. I just don't know what went wrong!

**Comment by Aquaeyes** [comment]
Okay, some more information, it seems to work when it's not based upon Optifine. Optifine may be incompatible?

**Comment by killjoy1221** [comment]
Can I have a log?

**Comment by killjoy1221** [comment]
Are you going to give me the log? I can't resolve this until you do.

**Comment by Aquaeyes** [comment]
Sorry, was having trouble with internet, the ISP decided we weren't a member anymore.

log:

https://docs.google.com/document/d/1Ke2kN31qg7KwNkcWNODayIsJvR1TymY1Ctlbwn3F0jA/edit?usp=sharing

**Comment by killjoy1221** [comment]
Use Minecraft 1.10.2.

**Comment by Aquaeyes** [comment]
Ah, allright, thank you! I didn't know because it didn't say on the website, could I suggest adding that?

Thanks again!

**Comment by killjoy1221** [comment]
The version of minecraft it is for is in the filename. `mc1.10.2`
