### ISSUE TITLE
1.12.2 gradlew grgit error

### ISSUE THREAD

**Issue by Creampony** [MineLittlePony/MineLittlePony#170]
Getting "build failed" every time I want to do something with sources using gradle.
"Could not get unknown property 'grgit' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension."
![изображение](https://user-images.githubusercontent.com/33199697/85229580-21941880-b3f3-11ea-9acf-908f535c43e6.png)

**Comment by killjoy1221** [comment]
You need to clone the repo using git, not just download the sources zip.

**Comment by Sollace** [comment]
First, make sure you have installed git:
`sudo apt-get install git` if you're on linux, or get it from their website <a href="https://git-scm.com/downloads">here</a>

After that run this command in a command window in any folder:
`git clone https://github.com/MineLittlePony/MineLittlePony.git`
and it will download the repo into a sub-folder: `MineLittlePony`

Recommended way is to make a fork on github and clone that so you have your own personal copy you can push to if you're looking to contribute.
