### ISSUE TITLE
Shields with banner designs are white on unicorn skins

### ISSUE THREAD

**Issue by BackgroundPony** [MineLittlePony/MineLittlePony#174]
Initially noticed on my server when players wondered why their shields were white. I think it is related to just the unicorn skin variant for some reason because testing with a pegasus/earth pony skins the shield shows properly. I tested in singleplayer with no other mods, same thing.

**Comment by ZacharyRMcKee** [comment]
This also applies to alicorn skins, and the shield's banner will appear at certain camera angles and/or distances to the shield's surface. 

Maybe something to do with the magical aura?

![image](https://user-images.githubusercontent.com/23197506/89362477-9f566f80-d693-11ea-9f63-acc94a9968ce.png)
![image](https://user-images.githubusercontent.com/23197506/89362498-abdac800-d693-11ea-9f44-8397ddbe7432.png)


Obviously a modded install but I have also witnessed this issue without other mods installed as well.
