### ISSUE TITLE
1.16.2 crash on launch

### ISSUE THREAD

**Issue by joeyjumper94** [MineLittlePony/MineLittlePony#176]
it happens when you use the latest release with 1.16.2
only fabric-api-0.18.0+build.397-1.16.jar and MineLittlePony-4.1.1-1.16-rc1.jar were used.
[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/5127670/latest.log)

**Comment by PCelestia** [comment]
it isn't updated to 1.16.2 yet, use 1.16.1 for now
