### ISSUE TITLE
minecraft pe Addon

### ISSUE THREAD

**Issue by Gamedestroyer112** [MineLittlePony/MineLittlePony#178]
Dear creator. I have no access to the computer for which this system is required to run on. I know I can import it to mcpe Addons, but how do I do that on mobile? Could you create a Mine Little Pony PE version of this Addon? Plz contact me back at: [email deleted]
Be sure to put in the subject box Mine Little Pony Response. That way I know it’s you. Thank you.

**Comment by Sollace** [comment]
We don't work with pocket edition. Sorry.
