### ISSUE TITLE
MineLP causing mc to freeze

### ISSUE THREAD

**Issue by Johnny4life** [MineLittlePony/MineLittlePony#18]
Minecraft freezes either on joining a server or as soon I hit tab to see the player list, started with hanging after pushing tab then today it started freezing instead.

There are no crash logs during this since I have to force quite Minecraft.

MC Version: 1.10.2
Mod Version: Forge 2089, liteloader 1.10.2 snapshot (unknown version, downloaded 06.09.16),
MineLP 1.10.2.2-mc1.10.2
Mods loaded:
Forge, Liteloader (from mods folder) and MineLP

**Comment by Aquaeyes** [comment]
The same has just started to happen to me as well, without crash logs too.

Forge, Liteloader, MC 1.10.2.

**Comment by Aquaeyes** [comment]
Aaaaaand it's fixed.
