### ISSUE TITLE
I cannot change the skin

### ISSUE THREAD

**Issue by Maksonchik76** [MineLittlePony/MineLittlePony#180]
I cant change skin because it gives an error.
![Desktop Screenshot 2021 01 15 - 16 02 39 03](https://user-images.githubusercontent.com/49066611/104731025-254f0a00-574c-11eb-9b63-343421fe68cb.png)
I dont now what to do.

**Comment by Sollace** [comment]
Update HDSkins https://github.com/MineLittlePony/HDSkins/releases/tag/v6.3.4-mc1.16.4
