### ISSUE TITLE
Head appears to be misplaced

### ISSUE THREAD

**Issue by ewewukek** [MineLittlePony/MineLittlePony#182]
mod version: 4.2-1.16.2
fabric loader version: 0.11.1-1.16.4
fabric api version: 0.30.0+1.16
hdskins version: 6.3.5-1.16.4

head appears to be too high:

![ugly-neck](https://user-images.githubusercontent.com/18519775/107269791-27f70380-6a5b-11eb-9ed0-cc79af9df2be.png)
![standing](https://user-images.githubusercontent.com/18519775/107269133-3133a080-6a5a-11eb-9799-bb1a1d05382e.png)
![boat](https://user-images.githubusercontent.com/18519775/107269148-355fbe00-6a5a-11eb-9853-3285b0cd247e.png)

i've moved head's pivot 1 up and got these results, but i'm not sure that is a correct fix

![standing-patched](https://user-images.githubusercontent.com/18519775/107269360-8cfe2980-6a5a-11eb-9ece-8ed56d0469cb.png)
![boat-patched](https://user-images.githubusercontent.com/18519775/107269368-8ec7ed00-6a5a-11eb-828b-ca5794b5e4e5.png)

**Comment by Sollace** [comment]
What size do you have set for your skin?

**Comment by ewewukek** [comment]
sorry for late answer, i've set it to #53beff Yearling
i've tried other sizes, some have similar problem

**Comment by Sollace** [comment]
Tall, Lanky, and Yearling models are indeed supposed to have longer necks. The clipping/exposure of the top of the neck shouldn't be happening, though, so I've made some adjustments.
