### ISSUE TITLE
cant change skin

### ISSUE THREAD

**Issue by zuzu428** [MineLittlePony/MineLittlePony#185]
how to change pony skin ??i cant change skin ...because it say ( sun.security.provider.certpath.suncertpathbuilderexception: unable to find valid certification path to requested target ) and i dont know what it this??? pls help me !! QWQ

**Comment by Sollace** [comment]
> The skin server uses Let's Encrypt for HTTPS certificates. Unfortunately, the version of Java Mojang ships with Minecraft does not like this. This leaves you with 2 options.
>
> 1. Update Java and tell the launcher to use it
>
> 2. Install this mod. https://www.curseforge.com/minecraft/mc-mods/letsencryptcraft-fabric
