### ISSUE TITLE
Crash at startup in 4.0.10 for MC 1.15.2

### ISSUE THREAD

**Issue by theblackwidower** [MineLittlePony/MineLittlePony#186]
Title says it all, really. I start it up, and it just crashes. I'm using MultiMC, and I installed nothing but Fabric, and the three mods, Fabric API, Mine Little Pony, and HDSkins, and it just crashes. Don't know what to do. I'm attaching the crash report. Hopefully someone can offer some insight.

[crash-2021-06-18_09.12.41-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/6677232/crash-2021-06-18_09.12.41-client.txt)

**Comment by Sollace** [comment]
You need to use Java 8 for any versions prior to 1.17

**Comment by theblackwidower** [comment]
I thought I was.

**Comment by theblackwidower** [comment]
Fixed. That honestly surprises me. I've never had that problem migrating to a new java version, where my old code would just break and I'd have to write it for the new version.

**Comment by Sollace** [comment]
There's a lot that changed between Java8 and Java16, and since Mson relies on some of the things they change (reflection access) it needed some slight rewrites in order to work.
