### ISSUE TITLE
Odd red tint on all some held items

### ISSUE THREAD

**Issue by backgroundman** [MineLittlePony/MineLittlePony#188]
mods: only Minelp (4.3.2) and Fabric Api (0.36.0)
![red_sus](https://user-images.githubusercontent.com/66832473/122801934-5b0f9600-d28a-11eb-818b-da67da707501.png)
Issue in first 1.17 and latest (4.3.2) release
Does not appear to be specific to pony type

**Comment by ghost** [comment]
I'm on MineLittlePony 4.3.2 alongside Fabric API 0.36.0 and HDSkins 6.4.6.

It seems to be the hurt colour overlay- it matches if I hurl myself off some blocks anyway!

For some reason this applies to:
- All blocks
- Most of the decorative blocks category (with the exception of glass panes, armour stand, heads, item frame, painting)
- All redstone items
- Rails
- Some miscellaneous items (beacon, turtle egg, conduit, string, wheat seeds, powdered snow bucket (NONE of the other buckets fyi), cocoa beans, pumpkin seeds, melon seeds, nether wart, beetroot seeds)
- Some food items (cake, carrot, potato, glow berries)
- No tools (I checked them all- figured I'd mention the category despite there being 0)
- Shields and tridents. The crossbow is _not_ affected.
- Cauldrons. No other brewing items
Before I went through basically the entire list by hand, I took these screens of randomly assorted items:
![image](https://user-images.githubusercontent.com/38290954/122830773-19620800-d2e9-11eb-82a7-dba236473400.png)

**Comment by Sollace** [comment]
Of course I'm kind of colour-blind, so I hardly noticed.
