### ISSUE TITLE
Pony's texture problems 1.17

### ISSUE THREAD

**Issue by dmkenza** [MineLittlePony/MineLittlePony#191]
I use mod. 
morevillagers-FABRIC-1.17-2.1.1.jar

And i see bug with rendering extra villagers.

![2021-10-26_23 04 33](https://user-images.githubusercontent.com/66675746/138953298-ac9741a5-2fc5-44dd-a39c-3edb2625b268.png)

**Comment by Sollace** [comment]
You need to add the missing textures, since we don't ship skins for non-vanilla villager types.
