### ISSUE TITLE
Nitwits/Unemployed villagers are broken.

### ISSUE THREAD

**Issue by AtomicGlow** [MineLittlePony/MineLittlePony#194]
The feature to overide Nitwits with specific textures is broken.

Not even the built-in batpony texture for taiga biomes loads. (assets\minelittlepony\textures\entity\villager\pony\taiga\nitwit.png)

https://media.discordapp.net/attachments/456608421152686080/925057330989654097/unknown.png?width=1029&height=579

Edit: It also applies to Zombies spawned in a biome.
https://media.discordapp.net/attachments/456608421152686080/925059858229776434/unknown.png?width=1029&height=579

**Comment by Sollace** [comment]
Are your villager's professions set to nitwit, or are they "none"? Because they're different, and villagers set to nitwit will have varied textures whilst villagers with no profession at all use the generic villager texture (no specific profession or biome texture).

**Comment by AtomicGlow** [comment]
Ah, you told me in the discord the unemployed villagers were supposed to use the nitwit texture.

**Comment by Sollace** [comment]
Nah, sorry. I misremembered.
