### ISSUE TITLE
4.4.4 Armor Stands not ponified

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#198]
Not sure if this option was removed, but armor stands aren't changed and the "objects" toggle in the ponfication menu has no effect.

**Comment by Sollace** [comment]
Have you renamed the armor stands to "Ponita" using a name tag?

That is required for them to render as pony armor stands, as it could otherwise mess with existing builds.

**Comment by derram** [comment]
That was it, thanks!

As a sidenote, they seem to have decent compatibility with the Statues datapack from vanilla tweaks.
