### ISSUE TITLE
Invisible bug

### ISSUE THREAD

**Issue by midnightBlaze18** [MineLittlePony/MineLittlePony#20]
When using the MineLittlePony mod with the latest version of both the mod and litleloader. And then having Optifine with the same latest version every now and again you become invisible and everyone around you. After 5 seconds to 2 mins you and everyone else reappears. this happens both on single and multiplayer.

**Comment by killjoy1221** [comment]
Are there any errors in the log?

**Comment by killjoy1221** [comment]
Update to OptiFine 1.10.2_HD_U_D4
