### ISSUE TITLE
Camera is pointed straight down or up when exiting a nether portal

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#201]
Direction is determined based on which direction past center the view was when entering the portal. 

Setting ponification to humans only stop the behavior.

**Comment by Sollace** [comment]
Make sure you're not using any other mods that mess with the camera. We don't change anything other than the height and I've never seen this happen using Mine Little Pony on its own ao I doubt it has anything to do with this mod.

**Comment by derram** [comment]
After poking around, it seems to be an interaction between MineLP and [Logical Zoom.]( https://www.curseforge.com/minecraft/mc-mods/logical-zoom)

Doesn't happen with one or the other disabled or if ponification is set to humans only.

**Comment by Sollace** [comment]
Hm. Weird.

They seem to be only changing the field of view. 

For now you can turn off the fillycam option, as a workaround. The camera won't match the model, but it should no longer cause you to look up wheb using logical zoom.

**Comment by derram** [comment]
I just disabled Logical Zoom for now. 

I've been using MineLP for so long, my entire world is designed around that fillycam camera height -w-

Thanks for helping me figure it out, that was driving me nuts.

**Comment by derram** [comment]
Oh, and here's my modlist if you're still curious about this. 

![Selection_1715](https://user-images.githubusercontent.com/5730335/167288343-590292c2-b177-4bc2-9d2a-e651be636e74.png)

**Comment by derram** [comment]
Well, turns out I was wrong and the problem is just really inconsistent in singleplayer but happens every time on a server. 

Happens with every other mod not only disabled but completely moved out of the mods folder, stops when MineLP and hdskins are disabled. 

Might be an interaction with Spigot.

**Comment by derram** [comment]
Spun up a vanilla server and it's happening there as well, so it's not Spigot. Might have something to do with that old bucket placing bug, I've been running into that one again recently.  

Some things I've found from testing:

View change is most extreme in survival, in creative the difference is barely noticeable. 

In singleplayer you have to be looking at a steep angle to get it to trigger, but in multiplayer it's consistent when just looking straight ahead. 

![singleplayer](https://user-images.githubusercontent.com/5730335/167293611-dc7b4ef6-9bce-410a-822b-da43f74b7097.gif)

![multiplayer](https://user-images.githubusercontent.com/5730335/167293632-d513a9d9-33dc-4d40-93df-75e2abbcd29b.gif)

**Comment by derram** [comment]
Okay, did more testing, no change for any of the following:

Created a new instance, updated fabric, fabric api, and lwjgl to the most recent versions, switched from openjdk to oracle java 17, switched from multimc to polymc.

That's everything I can think of aside from trying it with the vanilla launcher, which I can't do because that hasn't worked for me for months after an update started throwing an error saying "Failed to create launcher path, exiting early: Not a directory
"

Someone else on the server was able to replicate, but it only happened once after a few trips back and force through the portal. Might be something with Linux since he uses windows.

**Comment by Sollace** [comment]
Hm. I use windows as well.

Regardless, I can't do anything right now, but I'll check this as soon as I can.

**Comment by MimzyFang** [comment]
From my testing, this issue seems to be entirely caused by fillycam 
I only loaded up MineLittlePony Fabric API and HD Skins and as long as fillycam was on the issue persisted
