### ISSUE TITLE
Unable to start singleplayer world

### ISSUE THREAD

**Issue by PrinceDrowsy** [MineLittlePony/MineLittlePony#205]
https://imgur.com/a/p09oBhu

Been getting this error message whenever I try to start a new world. I have flappy elytras enabled in config if that info is needed for bug testing

**Comment by Sollace** [comment]
Oh, that's an _oof_

**Comment by Sollace** [comment]
Try the new version https://github.com/MineLittlePony/MineLittlePony/releases/tag/4.5.1

**Comment by PrinceDrowsy** [comment]
> Try the new version https://github.com/MineLittlePony/MineLittlePony/releases/tag/4.5.1

Works! Forgot to respond, sorry
