### ISSUE TITLE
Villagers missing their clothing/accessories. 

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#207]
Not sure if this was intentional because of the optimizations but only saddlebags are showing on villagers now. All other accessories are missing.

![2022-06-18_07 28 55](https://user-images.githubusercontent.com/5730335/174437973-025285bf-36bc-400a-9530-1e181dcb09d2.png)
![2022-06-18_07 31 32](https://user-images.githubusercontent.com/5730335/174438008-817ab1ad-e339-4dfd-839c-75eaf089f1fa.png)
![2022-06-18_07 31 15](https://user-images.githubusercontent.com/5730335/174438025-fbf6307f-f2f1-428f-a74f-46e6e3de456a.png)
![2022-06-18_07 31 39](https://user-images.githubusercontent.com/5730335/174438075-8a86f9ad-1163-4974-bd57-4c4f80001a56.png)

**Comment by derram** [comment]
@Sollace just a heads up, Mine Little Pony and HD Skins seem perfectly compatible with this project that allows fabric mods to be loaded in forge: https://github.com/Sinytra/Connector

**Comment by Sollace** [comment]
> @Sollace just a heads up, Mine Little Pony and HD Skins seem perfectly compatible with this project that allows fabric mods to be loaded in forge: https://github.com/Sinytra/Connector

Thanks for the notice. [I am already aware.](https://github.com/Sinytra/Connector/discussions/12#discussioncomment-6695107)
