### ISSUE TITLE
Grey boxes and crash on loading/joining worlds/servers

### ISSUE THREAD

**Issue by ZeldaLinkAaron** [MineLittlePony/MineLittlePony#21]
Windows 7 Ultimate 
Nvidia GTX 760 
AMD Phenom II x4 965
10Gb DDR3 RAM
Minecraft 1.10.2 

Mods
-Forge 1.10.2-12.18.2.2099
-Lightloader 1.10.2-00
-Mine Little Pony 1.10.2.6

Log 
-[2016-11-26-3.log.gz](https://github.com/MineLittlePony/MineLittlePony/files/614180/2016-11-26-3.log.gz)
-[fml-client-3.txt](https://github.com/MineLittlePony/MineLittlePony/files/614193/fml-client-3.txt)
Crash after joining world
-[crash-2016-11-26_05.24.07-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/614182/crash-2016-11-26_05.24.07-client.txt)
Grey boxes 
![image](https://cloud.githubusercontent.com/assets/19410292/20640042/57ad5dda-b39a-11e6-8cf1-2c2dfeeea75c.png)
-Still has grey boxes after adding a file using drag and drop or browse

**Comment by killjoy1221** [comment]
If anyone finds this later, this was solved by redownloading the liteloader installer. There was an error in his.
