### ISSUE TITLE
Incompability with Fabric Tailor

### ISSUE THREAD

**Issue by KristalAndStarlight** [MineLittlePony/MineLittlePony#210]
Fabric Tailor is a mod that let's you change skin from a file, url and existing players, it would be nice if compability was added.

**Comment by Sollace** [comment]
If Tailor is changing the player's skin then I don't see any reason why this mod wouldn't work with it as-is. We get the skin from the player and read the trigger pixels off of that, so if you upload a pony skin to whatever server Tailor uses, and they do their job properly, Mine Little Pony should work with it just fine.

**Comment by KristalAndStarlight** [comment]
Ok sorry, it does work, we just tried a skin that didn't work lol. But after trying a different one, it does work.
