### ISSUE TITLE
Slim skins don't work for humans

### ISSUE THREAD

**Issue by Idze** [MineLittlePony/MineLittlePony#216]
You can't use slim/Alex skins as a human 
![slim](https://user-images.githubusercontent.com/61480413/179125457-dbe69e3e-1f1e-4aab-b9af-12232921ea44.png)

**Comment by Sollace** [comment]
You have to use the buttons on the right to switch to the slim arm model.

**Comment by Idze** [comment]
> You have to use the buttons on the right to switch to the slim arm model.

I did, you can se the the yellow button is pressed down

**Comment by Sollace** [comment]
> > You have to use the buttons on the right to switch to the slim arm model.
> 
> I did, you can se the the yellow button is pressed down

Ah, okay, sorry. I couldn't tell because of the resource pack. I might have to look at this later as it might be an interaction with the Mine Little Pony mod.

**Comment by coppercore** [comment]
I can confirm this happening as well, had my son trying to load a slim human skin and it just didn't seem to work right.
