### ISSUE TITLE
crash on server join

### ISSUE THREAD

**Issue by edowski** [MineLittlePony/MineLittlePony#218]
[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/10096054/latest.log)
hi my game crashesh every time i try to join a server id doesnt happen on single player it works normaly after disabling the mod

**Comment by Sollace** [comment]
One of your mods is not compatible and is breaking our armour stand renderer with their mixins (see previous issue about Figura).

I can't fix this. You have to figure out which mod it is and report it to them, or turn off "ponify objects" in the settings so armour stands don't get converted.
