### ISSUE TITLE
Unicorn horns aren't properly attached to the head.

### ISSUE THREAD

**Issue by MyUsernameDoesntMatter** [MineLittlePony/MineLittlePony#22]
![2016-12-10_10 12 32](https://cloud.githubusercontent.com/assets/20265984/21069903/df631dfa-bec1-11e6-9d9b-d4454e45e395.png)

It appears to be an issue with skeletons as well.

![2016-12-10_10 16 04](https://cloud.githubusercontent.com/assets/20265984/21069907/e426acf8-bec1-11e6-89f1-dc028f3f697f.png)

**Comment by killjoy1221** [comment]
I already fixed this. Update.

**Comment by killjoy1221** [comment]
0c0a42be119298099e4437354cac46e6a0c38b6d
