### ISSUE TITLE
Pony villagers makes fps drop

### ISSUE THREAD

**Issue by dmkenza** [MineLittlePony/MineLittlePony#222]
Hi. 

I have modpack with a lot of optimization mods such as Sodium and Iris Shaders. My shaders was enabled.

I saw fps drop when I look at around 10 pony villagers at once from 60 fps to 30 fps =(
When I disable Mlp villagers from settings from F9 back to normal minecraft villagers I see 60 fps.

If i use vanila with only MLP mod without shaders on same map:
Normal villagers - 40 fps
MLP villagers - 30 fps

Pony models cause fps drop. They don't look as super complex.

**Comment by Sollace** [comment]
Believe me it's already a lot better than it was. I'll look into other ways I can improve it. At the moment, though, I can't really see any difference between pony villagers and vanilla villagers when not using shaders.
