### ISSUE TITLE
Armors from  Twighlight Forest have bad rendering

### ISSUE THREAD

**Issue by dmkenza** [MineLittlePony/MineLittlePony#225]
Is it possible to fix this?

![2023-01-19_15 21 28](https://user-images.githubusercontent.com/66675746/213442395-35c6f4fc-14db-4a0f-9fea-83f63d08026b.png)
![2023-01-19_15 21 36](https://user-images.githubusercontent.com/66675746/213442403-fde6c179-81ec-4d7e-b6a0-53dcc8c95304.png)

**Comment by MimzyFang** [comment]
You could do a resource pack to fix it

**Comment by Sollace** [comment]
Yeah, a resource pack might be neccessary here since the armour is very non-standard.
