### ISSUE TITLE
Ponified Villagers textures not showing correctly

### ISSUE THREAD

**Issue by coppercore** [MineLittlePony/MineLittlePony#228]
Minecraft 1.19.3
MineLittlePony 4.7.4

Something odd is happening with Ponified villager textures, see below:
![image](https://user-images.githubusercontent.com/35123789/221381334-da7bb6c2-991f-45de-910b-c3b9b9bee3d9.png)
![image](https://user-images.githubusercontent.com/35123789/221381340-ee2b4bb4-a578-4784-8808-98b888a5b076.png)
![image](https://user-images.githubusercontent.com/35123789/221381346-6eb771ec-41b8-450d-bb4c-8fe97e871b26.png)
![image](https://user-images.githubusercontent.com/35123789/221381348-3d8632c2-43fa-494e-aa8f-dbe1c746201d.png)
![image](https://user-images.githubusercontent.com/35123789/221381379-1d02080f-8b7a-481f-81aa-ee7f2dbb96d1.png)

**Comment by Sollace** [comment]
Did you rename your villagers?

Looks like it's using player skins relating to the names you picked.

**Comment by coppercore** [comment]
I had the mod Villager Names renaming villagers, so it would seem that... is a thing now?

It wasn't doing it in 1.19.2, but I'm not going to worry about it. Just something to watch out for. That's very interesting though as I'd never seen it happen before with 1.19.2 version of MineLP and Villager Names.

**Comment by Sollace** [comment]
It was a hidden feature added in 1.19.3. But no worries! Updated version fixes it so at least they don't try to use human skins.

For future reference:
You can rename a villager with a name tag and it will first try to use a skin from the list of background ponies.
Fluttershy -> fluttershy.png
Pinkie Pie -> pinkie_pie.png

If it doesn't match a background pony skin, it will instead try to find a player with the same name and adopt it's skin.
Sollace -> sollace.png

**Comment by coppercore** [comment]
![image](https://user-images.githubusercontent.com/35123789/231268013-7a3371f7-f470-4022-aae2-dbb2ef49eda0.png)

FYI looks like this is happening once again with MineLP v4.8.7+lts.1.19.3.

I also looked up the generated name of the villager in question and there is not a matching skin on the HDSkins server:
![image](https://user-images.githubusercontent.com/35123789/231268320-cbcc3765-8d2b-48e4-bd6e-f60701ad4b7d.png)

**Comment by coppercore** [comment]
To confound this even more, I just toggled Villager ponification in MineLP settings, and it went away.

I can't seem to reproduce it now. Damn.

Obviously something DID happen, but I'll have to try other methods and see if it happens to others.
