### ISSUE TITLE
Pony saddlebag texture not displaying correctly from player skin

### ISSUE THREAD

**Issue by coppercore** [MineLittlePony/MineLittlePony#229]
Minecraft 1.19.3
MineLP 4.7.4
HDSkins 6.7.6

In HDSkins when you preview your skin model (if you have saddlebags defined in your skin), you'll see the saddlebags with the custom texture as shown below, but ingame, it's showing what looks like a defaulted texture:

HDSkins Preview:
![image](https://user-images.githubusercontent.com/35123789/221381479-35c8d5a3-5730-46df-b500-eb2351d47053.png)

Ingame:
![image](https://user-images.githubusercontent.com/35123789/221381783-6d9f4ea3-ef8e-4165-a76a-9b27ffaf9249.png)

**Comment by Sollace** [comment]
Try uploading a separate saddlebags texture in the skinning gui as a workaround.
I'll see about fixing the rendering for the old method later.

**Comment by coppercore** [comment]
That did work, by toggling through and selecting saddlebags, then uploading the full skin again.
