### ISSUE TITLE
The game crashed whilst rendering entity in world

### ISSUE THREAD

**Issue by Phoenix616** [MineLittlePony/MineLittlePony#230]
Game crashes while trying to join certain servers/worlds. Disabling "Pony Skulls" option seems to stop it.

```
The game crashed whilst rendering entity in world
Error: java.lang.IllegalStateException: Model file for minelittlepony:dj_pon_three was not loaded!
```

[crash-2023-03-08_20.40.09-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/10924467/crash-2023-03-08_20.40.09-client.txt)

**Comment by Sollace** [comment]
I still don't know what causes this! D:

Disabling pony skulls is the workaround for now, as the problem occurs when trying to render player skulls and for some reason that particular model just doesn't get loaded when in a multiplayer context.

**Comment by Sollace** [comment]
Can you please also send your client's log?
