### ISSUE TITLE
Mixin apply fails on 1.19.4

### ISSUE THREAD

**Issue by jane0009** [MineLittlePony/MineLittlePony#231]
Hello, I have run into a crash while using a PrismLauncher instance with the mod installed - it would crash, being unable to apply a mixin.

I created a test instance for both fabric and quilt, and the same issue was present.

log using fabric: https://mclo.gs/AXYPuxr
log using quilt: https://mclo.gs/ndqO6HM

It seems to me like the minecraft class in question was removed or refactored in the 1.19.4 update.

**Comment by MimzyFang** [comment]
The mod has not been updated for 1.19.4 yet

**Comment by jane0009** [comment]
Ah, okay.
