### ISSUE TITLE
Tail is not showing

### ISSUE THREAD

**Issue by Qoolize** [MineLittlePony/MineLittlePony#234]
**Hello!**

**in MC 1.19.4, the Tail is not showing. I tried to load the mod separately, same problem.
Thanks for the help.**

> for more information, please ask.

**Comment by MimzyFang** [comment]
1. what version of the mod are you using, there have been multiple revisions already due to bugs
2. what species does your skin have
3. can you provide screenshots

**Comment by Sollace** [comment]
The tail looks fine on the player when I've tested it, so some more info will be required.

**Comment by Qoolize** [comment]
i thought i added a screenshot. i was to fast...sry.
I use the newest version: 4.8.2 
see Screenshot

![2023-03-29_21 49 11](https://user-images.githubusercontent.com/126105754/228651490-d1b938db-192b-4e1c-b70f-ab4d344350e0.png)

from the log:
> [21:20:02] [Render thread/INFO]: Got pony data on the CLIENT from 6b5bd775-6074-47fc-849e-a58fe2704896 with set skin and he is a EARTH!
> [21:20:02] [Server thread/INFO]: Got pony data on the SERVER from 6b5bd775-6074-47fc-849e-a58fe2704896 with set skin and he is a EARTH!
> [21:20:02] [Render thread/INFO]: Reloading entity icon resources...
> [21:20:02] [Render thread/INFO]: Done!
> [21:20:06] [Render thread/INFO]: Sending pony skin data over as we are either in single-player or lan
> [21:20:06] [Render thread/INFO]: Got pony data on the CLIENT from 6b5bd775-6074-47fc-849e-a58fe2704896 with set skin and he is a ALICORN!
> [21:20:06] [Server thread/INFO]: Got pony data on the SERVER from 6b5bd775-6074-47fc-849e-a58fe2704896 with set skin and he is a ALICORN!


Maybe this will help, theres a little flickering on the skin:
![hdfrjdr](https://user-images.githubusercontent.com/126105754/228657314-e357aa03-3557-4f2d-ad81-4fbebb458760.gif)
