### ISSUE TITLE
Incorrect Seapony Texturing

### ISSUE THREAD

**Issue by Nathin-Dolphin** [MineLittlePony/MineLittlePony#236]
<img width="481" alt="Screenshot_20230404_232519" src="https://user-images.githubusercontent.com/60240236/230150820-5cc0ceda-67cd-4310-b7de-099c8ca82634.png">
The top is Minecraft 1.19.2, MineLP 4.7.5+lts, and HD Skins 6.7.6+lts.

The bottom is Minecraft 1.19.4, MineLP 4.8.5, and HD Skins 6.8.0. (It also has other mods but I ran Minecraft again with only those three mods and it looks the same.)

Through mine and Cupute's testing, we have only gotten the transformation to work if both the 'Player Texture' and 'Seapony' are the same skin.

The left skin is 
![seapony 2](https://user-images.githubusercontent.com/60240236/230152241-3f244d63-88c8-4f11-9888-519d0cc0f6bb.png)
and the right skin is 
![MineLP Sea Wyvern (Sea Pony)](https://user-images.githubusercontent.com/60240236/230152143-19e05673-2d0f-48fa-a71c-1ee0b7062500.png)

It appears as though the second layer is not being hidden.

**Comment by Sollace** [comment]
I see nothing wrong with seaponies
![image](https://user-images.githubusercontent.com/6429283/230886441-b03dfdd9-4e20-4ef6-97bf-5be4aa2f056a.png)

**Comment by Sollace** [comment]
![image](https://user-images.githubusercontent.com/6429283/230887211-6d3fd17d-b632-44f3-a197-216567d97ad6.png)

**Comment by Sollace** [comment]
![image](https://user-images.githubusercontent.com/6429283/230889300-46926934-e523-4e5c-8e95-7630195e276c.png)
![image](https://user-images.githubusercontent.com/6429283/230889354-fc022aff-5a15-4157-a7ad-6a922e97020c.png)

**Comment by Sollace** [comment]
![image](https://user-images.githubusercontent.com/6429283/230889459-3f4aed81-dfb8-447f-9195-3762e6dab60c.png)

**Comment by Sollace** [comment]
Finally managed to reproduce it. Seems to only happen in the production version of the game, which is annoying. :/
