### ISSUE TITLE
Issue with Cosmetic armor mod

### ISSUE THREAD

**Issue by LuckyDusk** [MineLittlePony/MineLittlePony#237]
Armor placed in the cosmetic slot doesn't show up on pony models.
![2023-04-08_23 26 33](https://user-images.githubusercontent.com/19485053/230752702-c9c7ea10-ea72-4cff-a8ce-72a95f6fd477.png)

![2023-04-08_23 26 06](https://user-images.githubusercontent.com/19485053/230752708-06fe8232-51e4-460f-8626-4758e36a9bfe.png)

https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric

**Comment by coppercore** [comment]
I can also confirm this happens with this cosmetic mod in my own testing.

If support for this is implemented, this would also allow a player to get around any oddball mod armors that use a different texture from the standard armor texture so they don't just have a solid color covering their pone. Twilight Forest and Botaina are both examples of mods that use nonstandard armor textures.

**Comment by Sollace** [comment]
This isn't really something I can add support for. As for the issue of supporting modded armour, [we have support for custom models](https://github.com/MineLittlePony/MineLittlePony/blob/1.20/src/main/java/com/minelittlepony/api/model/armour/ArmorModelRegistry.java#L16). I encourage people to learn how to use them.
