### ISSUE TITLE
Shader pack unicorn item glow oddity

### ISSUE THREAD

**Issue by coppercore** [MineLittlePony/MineLittlePony#241]
On MC 1.19.3 with Iris 1.5.2, (MineLP 4.8.7+lts.1.19.3)  there's a strange square box effect that happens with the magic glow. Tested on several shaders, and it seems to happen on a few of them. See below:

ComplementaryReimagined_r2.0.3:
![image](https://user-images.githubusercontent.com/35123789/231290294-504dff16-b496-4ad5-b41c-efb8ddb9c5b4.png)

Sidur's+Vibrant+Shades+v1.41+High:
![image](https://user-images.githubusercontent.com/35123789/231290386-f707a6b3-47ac-4b3b-9dac-239f80373630.png)

Some less intensive shaders don't cause the effect, and it only happens to enchanted items levitating in a unicorn's hold in first or third person. Turning off unicorn levitation in MineLP settings makes the issue go away.

**Comment by coppercore** [comment]
First Person View:
![image](https://user-images.githubusercontent.com/35123789/231291237-05d20961-9b88-4b03-840f-7519cd3a3349.png)

Enchanted Diamond Axe (3rd)
![image](https://user-images.githubusercontent.com/35123789/231291413-bb1a0449-d9f2-4fb1-a8e3-6b15367531a9.png)

Enchanted Diamond Axe (1st)
![image](https://user-images.githubusercontent.com/35123789/231291450-bffacc15-e043-42ec-af6d-662c7bd8bb45.png)

**Comment by Sollace** [comment]
Can't do anything about that unfortunately. This is the shaders doing something to alpha tests that is making the parts of the model that are normally invisible, visible.

**Comment by coppercore** [comment]
Would it be possible to have a toggle implemented for the glow effect around items for situations like this, where you can have the item hovering but without a glow?

I don't know what changed in Iris but it wasn't doing this before in a previous version.

Another example:
![image](https://user-images.githubusercontent.com/35123789/231530204-4149787c-4c7e-4c2c-a90f-8fb9ab78556d.png)

**Comment by stricq** [comment]
Are you saying this is a conflict with Iris itself?  Because it still happens even with shaders disabled.

I just tested this.  Even with Iris not loaded, no shaders possible, this still happens.  I do not believe, as you have stated, that this is an incompatibility with shaders.

Could this be related to the Minecraft glint changes?  Not sure, though.  Because this is happening in 1.19 as well.
