### ISSUE TITLE
[BUG] Severe framerate drop with MineLittlePony + non-vanilla armour

### ISSUE THREAD

**Issue by Evan555alpha** [MineLittlePony/MineLittlePony#243]
**Describe the bug**
When one has MineLittlePony installed, and is using the pony model, client framerate will drop more and more, as pieces of non-vanilla (i.e. mod-added) armour are equipped.
It appears to only happen in third person, or when the third-person model is otherwise loaded.

**To Reproduce**
Install MineLP, and have pony models enabled
Install mods that add armour sets - I've checked so far with *Spectrum*, *Tech Reborn*, and *Modern Industrialisation*.

**Expected behavior**
Wonky armour model/texture layout, but without the severe framerate loss.

**Mod version**
Minecraft 			1.19.2
MineLittlePony		4.8.7+LTS
Spectrum				1.6.9
Tech Reborn			5.4.0
Modern Industrialisation	1.6.3

And versions of everything else, just in case there's something else at play here
LWJGL 				3.3.1
Intermediary Mappings 	1.19.2
Fabric Loader 			0.4.19
Architectury 			6.5.69
Big Pony				1.7.3
Cloth Config			8.2.88
Fabric API			0.76.0
owo					0.8.5
Patchouli				1.19.2-77
Revelationary			1.3.3
Roughly Enough Items	9.1.595
Trinkets				3.4.2

**Screenshots**
![2023-04-13_14 17 55](https://user-images.githubusercontent.com/10338511/231651898-23f4544b-e240-4416-93a5-774603151884.png)
![2023-04-13_14 18 00](https://user-images.githubusercontent.com/10338511/231651907-e2011328-d0e2-46ff-a461-496f33b2cf78.png)
Large red spikes are when in the inventory GUI, so not all of it is due to equipped armour.
Orange is the general framerate when all armour pieces are equipped - in this case it's the crystal set from *Spectrum*.
Green is when no armour is equipped.
![2023-04-13_15 46 17](https://user-images.githubusercontent.com/10338511/231666898-813ef8a3-2540-4ad4-8a24-d3dae3a2260e.png)
This screenshot is in the modpack *All of Fabric 6*, v1.5.2, with *Tech Reborn's* Ruby armour set. Each major step down in frame time corresponds to one piece of armour being unequipped.

**Crash Report**
N/A

**Other Thoughts**
I first noticed this with the modpack *All of Fabric 6*, version 1.5.2, with *Spectrum's* crystal armour set. 
The first two screenshots above are from a minimalised environment with only Spectrum, MineLP, REI, and all relevant dependencies.
I fully expected armour pieces to not look right, since most modded armours won't look correct with MineLP, but I did not expect the framerate drop.
Unfortunately there's nothing in the logs that I can see, that pertain to rendering errors, but here's the [latest.log](https://github.com/DaFuqs/Spectrum/files/11218155/latest.log) from that minimal setup just in case.
I am unsure if my using of a skin with the changeling race set via trigger pixel is related to this issue.

**Comment by Evan555alpha** [comment]
Exploring a little further: the same frame drop happens with *Ad Astra's* spacesuit. Since I had previously worn the spacesuit in third person without issue, I checked again with a previous version of MineLP.
Reverting MineLP back to 4.7.5+LTS for 1.19.2, the issue is no longer present.
![2023-04-14_10 57 22](https://user-images.githubusercontent.com/10338511/231914183-bfc3996e-cff9-4681-96c9-b096e8c2c754.png)

**Comment by Sollace** [comment]
Can you maybe check that it also occurs in 1.19.3/1.19.4?

It may be that it's checking for custom armor models which is causing this, so I would probably expect it to affect those versions too.

**Comment by Evan555alpha** [comment]
1.19.3 did not have the issue when I checked using *Tech Reborn* with the following mod versions:
Architectury 7.1.78
Cloth Config 9.0.94
Fabric API 0.76.1
MineLP 4.8.7
Reborn Core 5.5.0
REI 10.0.596
Tech Reborn 5.5.0
owo 0.10.3
Trinkets 3.5.1

1.19.4 didn't either:
Architectury 8.1.79
Cloth Config 10.0.96
Fabric API 0.78.0
MineLP 4.8.7
Reborn Core 5.7.0
REI 11.0.597
Tech Reborn 5.7.0
owo 0.10.3 (1.19.4 beta release)
Trinkets 3.6.0

**Comment by Sollace** [comment]
Fixed in [4.8.8+lts1.19.2](https://github.com/MineLittlePony/MineLittlePony/releases/tag/4.8.8%2Blts1.19.2)
