### ISSUE TITLE
First Person Model compatibility issues

### ISSUE THREAD

**Issue by whitebear60** [MineLittlePony/MineLittlePony#244]
With the First Person Model mod installed and enabled, I see two inconsistencies at this point.

First, [I can see my neck while swimming](https://user-images.githubusercontent.com/42472132/235288941-45d0e019-6bea-4b21-b481-47f039d0381a.png)
Second, [I think something weird happens with my head disappearing and the rest of the body showing up if I turn around while climbing the ladder](https://user-images.githubusercontent.com/42472132/235288998-77171548-5455-4475-94e1-e648798d2fe4.png)

You can click the links to see the screenshots of the things I'm mentioning
MineLP 4.8.7

If you will need some additional information, feel free to comment here or message me elsewhere

**Comment by Sollace** [comment]
The head is purposefully hidden so it doesn't clip with your camera.

**Comment by whitebear60** [comment]
The neck messing up with the view in the first person while using the mod while swimming is still something that should be looked into, I think...
