### ISSUE TITLE
Sky Villages by Aureljz Add-on

### ISSUE THREAD

**Issue by PrinceDrowsy** [MineLittlePony/MineLittlePony#246]
An add-on for this mod that turns all the sky village villagers into pegasi would be very cute, and definitely add immersion in my opinion.

![image](https://github.com/MineLittlePony/MineLittlePony/assets/75338505/85f63e00-4f07-48b1-8a9d-641991a85fba)

**Comment by Sollace** [comment]
Oh I love that. Do you have a link to the mod?

It might be doable just by adding textures for them.

**Comment by PrinceDrowsy** [comment]
> Oh I love that. Do you have a link to the mod?
> 
> It might be doable just by adding textures for them.

I do! https://www.curseforge.com/minecraft/mc-mods/sky-villages-fabric

**Comment by Sollace** [comment]
Hm. The mod appears to be closed source. Might take a little longer to support it since I'll have to get a game together with the mod.
