### ISSUE TITLE
Crash with Entity Model Features when loading pony Skin 

### ISSUE THREAD

**Issue by MimzyFang** [MineLittlePony/MineLittlePony#247]
The game crashes when any pony skin gets loaded and the mod [Entity Model Features](https://modrinth.com/mod/entity-model-features) is installed
Log: https://mclo.gs/NCgUw81

Minecraft version: 1.20.1
Loader: Fabric Loader 0.14.21
Fabric API: 0.84.0+1.20.1
MineLP: 4.9.0
Entity Model Features: 0.2.11
Entity Texture Features: 4.4.4

**Comment by stricq** [comment]
Saw this one, too.  I just disabled EMF since I wasn't really using it.
