### ISSUE TITLE
getting skin hash from server hangs client

### ISSUE THREAD

**Issue by MamiyaOtaru** [MineLittlePony/MineLittlePony#25]
in getTextureHash(), readFirstLine(); hangs the client while the md5 is downloaded *from the internet*.

            return Resources.asCharSource(url, Charsets.UTF_8).readFirstLine(); 
is basically equivalent to 
            CharSource charSource = Resources.asCharSource(url, Charsets.UTF_8);
            BufferedReader in = charSource.openBufferedStream(); 
            String first = in.readLine();
            in.close();
            return first;
wherein  BufferedReader in = charSource.openBufferedStream();  specifically is the offender.

It's basically impossible to have this mod running on a busy server (Hypixel, say) as the client is stuck waiting for an md5 every time a new player pops up.  

just passing null as the hash to the HDProfileTexture constructor fixes this (of course then it's just getting Super's hash, and one might as well just use MinecraftProfileTexture like before)

If  having "a custom hash which is not the file name" is that important and it has to come from the server, a fix would be to, in a thread, request the md5, construct the HDProfileTexture without it and have the hash set when it comes through.  I might screw around with this and submit a pull, but my grasp of FutureTask or whatever will need to improve some first.

**Comment by killjoy1221** [comment]
I added that in to act as a client cache. With the future, I added that in because it was hanging the client. If I remember, every task is run on the same thread, so it will only show down the skin download tasks. 

As for the stream, it should only hang at that point if the domain either can't be found or the server is slow. Resulting in 404 or any other error code is handled cleanly. 

Anyway, the hash isn't even implemented on the server. I think I need to talk to mumfrey about that because I gave him the code for it. Either he didn't use that part or there's parts of the server unknown to me.

**Comment by MamiyaOtaru** [comment]
well yeah it will only hang _indefinitely_ if the domain can't be found.  But having the main thread wait for the reply is not good, unless you can guarantee the server's ping is 1 or something haha

Of course when getProfileData() is called from HDSkinManager.loadTexture() things are cool, since loadTexture() is called from getSkinLocation() and is wrapped in a runnable.  BUT getProfileData() is also called from MixinPlayerInfo.getSkinType(), which is injected into NetworkPlayerInfo.getSkinType() which is called from RenderManager.getEntityRenderObject(), from RenderManager.doRenderEntity(), from RenderEntities() from renderWorldPass() _on the main thread_

that is to say, rendering the world pauses while waiting for a file to download from the server.  That's not good :)

to see what I mean try logging into mc.hypixel.net and going to the arcade lobby, and watch everything pause every time a new player joins.  Or even better the *super* long pause when _you_ first log in and all the players already there are new to you and have their hashes requested.  It's readFirstLine() that's doing it

**Comment by killjoy1221** [comment]
Looks like you were right. I've got a fix working which I will push soon.
