### ISSUE TITLE
Minecraft Comes Alive Compatibility

### ISSUE THREAD

**Issue by PrinceDrowsy** [MineLittlePony/MineLittlePony#251]
The models of minecraft comes alive overwrites the pony models for the villagers. This is unfortunate, and it'd be nice if they were ponies again.

**Comment by Sollace** [comment]
This is something I'm aware of. i did work on MCA for a time and wanted to add support, but the way they render villagers is quite complicated and I wasn't really happy with swapping them out for a simple pony model.

It might happen as a separate addon, but probably not any time soon.
