### ISSUE TITLE
Control species with server command?

### ISSUE THREAD

**Issue by BlasterM5** [MineLittlePony/MineLittlePony#255]
Just a thought - it would be neat if species swapping could be automated from the server side via a command. Would make it easier for plugin / mod effects. Still be a client mod, if possible.

**Comment by BlasterM5** [comment]
Like, have the effect be temporary - only affects the player while on the current session in the server. When disconnect, it reverts to the skin's default.

**Comment by Sollace** [comment]
The mod is client-only. We don't do anything with the server.
