### ISSUE TITLE
Seapony skin not working correctly after 4.11.2 update

### ISSUE THREAD

**Issue by N1ghtTheF0x** [MineLittlePony/MineLittlePony#258]
Seapony skin before 4.11.2 (4.11.1):
![Screenshot 2023-11-05 212835](https://github.com/MineLittlePony/MineLittlePony/assets/60095145/2df58adf-9aa3-4fd2-bb67-d8e13aaebd6a)
Seapony skin after 4.11.2 (4.11.2+):
![Screenshot 2023-11-05 212732](https://github.com/MineLittlePony/MineLittlePony/assets/60095145/e8be82f5-5e98-44a6-9f6a-48a9a92de4b2)
For some odd reason it's using the main pony skin instead of the uploaded seapony skin or am I doing something wrong here?
Here's my main and seapony skin:
![LunarEclipse](https://github.com/MineLittlePony/MineLittlePony/assets/60095145/a599b5d5-dbd3-4a7f-8b41-1996b90facb1)
![LunarEclipseWater](https://github.com/MineLittlePony/MineLittlePony/assets/60095145/436660fd-977c-486f-a51c-2be5f55a4971)

**Comment by MimzyFang** [comment]
That's a issue with the 1.20.2 version
Downgrade to 1.20.1 if you can
