### ISSUE TITLE
Sodium Causes pony bodies to disapear

### ISSUE THREAD

**Issue by AdamDash** [MineLittlePony/MineLittlePony#260]
The Sodium mod causes the players body model to disappear. I have tested this with and without Sodium and it appears to be what is causing the problem. I am not sure if this is fixable or not since it is caused by another mod, but I thought it was worth reporting considering how useful Sodium is. 
![2023-12-30_11 38 59](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/6e66ea7b-a2d9-40be-9a17-a75efa18c413)

**Comment by MimzyFang** [comment]
Please let us know the versions of the mods you use

**Comment by AdamDash** [comment]
I used version 4.11.5 of Mine little Pony and Sodium Version 0.5.5 both on 1.20.2 Minecraft.

**Comment by MimzyFang** [comment]
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/1a6a0a4b-9b61-4a46-932c-28aa84b4c864)
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/e08fba49-e222-4e1a-8af5-0255f45e180e)
![grafik](https://github.com/MineLittlePony/MineLittlePony/assets/43648117/0dae3f3f-74f8-43e6-9003-cdf2194409cc)

trying to replicate the issue here with this pack and besides the minor issue with the tail that is already known I can't replicate your issue here can you send the game log

**Comment by AdamDash** [comment]
Okay, odd; do you need the game log after booting up the game or after a world has been loaded?

**Comment by MimzyFang** [comment]
> Okay, odd; do you need the game log after booting up the game or after a world has been loaded?

I mostly want it to see the mod list though it would also be useful to see if there are any errors and maybe if there is some weird stuff going on so after the world loaded and preferably you switched into third person

**Comment by AdamDash** [comment]
Okay, I have attached a screenshot of the mod list that I installed manually and text file containing the game log when the world is loaded and when I switch the third person.

![Screenshot 2023-12-30 172117](https://github.com/MineLittlePony/MineLittlePony/assets/65252885/b487a56b-378c-4ab6-864d-4ab9f5dcf719)
[Game Log.txt](https://github.com/MineLittlePony/MineLittlePony/files/13799912/Game.Log.txt)

**Comment by MimzyFang** [comment]
Could you share your latest.log file please the log you provided seems to be missing information 

You can find it in your .minecraft/logs folder

**Comment by AdamDash** [comment]
Okay my bad, that should be the correct file attached now. Also did not realize that I am on version 4.11.3 of the mod not 4.11.5
[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/13799933/latest.log)

**Comment by Sollace** [comment]
> Okay my bad, that should be the correct file attached now. Also did not realize that I am on version 4.11.3 of the mod not 4.11.5 [latest.log](https://github.com/MineLittlePony/MineLittlePony/files/13799933/latest.log)

Update to 4.11.5. That should resolve your issue. 🙂

**Comment by AdamDash** [comment]
> > Okay my bad, that should be the correct file attached now. Also did not realize that I am on version 4.11.3 of the mod not 4.11.5 [latest.log](https://github.com/MineLittlePony/MineLittlePony/files/13799933/latest.log)
> 
> Update to 4.11.5. That should resolve your issue. 🙂

Okay, yeah; that fixed it! My bad.

**Comment by MimzyFang** [comment]
Since this issue seems to be resolved can it be closed?
