### ISSUE TITLE
java.util.NoSuchElementException: Can't find part boob

### ISSUE THREAD

**Issue by ashymcgay** [MineLittlePony/MineLittlePony#267]
not sure what caused this, im new to this mod and player model editing so im lost as hell, but if its relevant, i removed a large ammount of mods until it didnt crash on startup, but now i can't change pony skins. heres a pastebin of the error https://pastebin.com/VTCbvTbT

**Comment by Sollace** [comment]
This has nothing to do with us or connector. This is the estrogen mod. I don't think it's compatible with other mods that change the player model.

**Comment by ashymcgay** [comment]
oh my gosh, im so sorry, okay, i cant read logs or crash reports, apparently! sorry about that
