### ISSUE TITLE
Flight Detection issue in 1.20.4, Changeling and Wings of Icarus user takes fall damage on landing

### ISSUE THREAD

**Issue by coppercore** [MineLittlePony/MineLittlePony#279]
In 1.20.4, if you are playing as a changeling, or are say a unicorn using the Wings of Icarus, you will take fall damage upon landing, based on what appears to be the highest point in your flight path. Fly high enough then land gracefully and it will be as if you jumped from a lethal height once your hooves make contact with the ground.

I have tested this in singleplayer and on a dedicated server as well, and the issue occurs.

Something that may help is an oddity I noticed with the Wings of Icarus not using any charge or taking durability damage when in flight.
![image](https://github.com/MineLittlePony/MineLittlePony/assets/35123789/0c5f010b-d81c-4ca2-80af-af55d2a4921d)

Also, this is all that appears in the server console when landing and dying:
![image](https://github.com/MineLittlePony/MineLittlePony/assets/35123789/4e49388f-019d-45dd-bcb6-96f895903401)

Steps to reproduce  in 1.20.4 (v1.3.6 Unicopia on Fabric)
1. Equip Wings of Icarus
2. Fly up
3. Land by descending with shift
4. Die, or take damage based on max height durning flight

**Comment by Sollace** [comment]
I cannot transfer issues to outside of the org. Please file it again at https://github.com/Sollace/Unicopia
