### ISSUE TITLE
Compatibility with the Sit mod

### ISSUE THREAD

**Issue by VaraHunter682** [MineLittlePony/MineLittlePony#280]
For some reason, pony models float slightly with this, and the camera renders inside the body. Please add support for the sit mod lol
![2024-05-11_20 21 34](https://github.com/MineLittlePony/MineLittlePony/assets/138996724/dbd93102-28b3-47bf-9f5a-9a942c6e8268)
![2024-05-11_20 32 38](https://github.com/MineLittlePony/MineLittlePony/assets/138996724/8e39cb2b-799f-4436-8b46-717f290cf688)

**Comment by Sollace** [comment]
What version are you using?

**Comment by VaraHunter682** [comment]
1.20.4, haven't updated yet, but willing to lol

**Comment by Sollace** [comment]
Alrighty, well riding position changed in 1.20.5 so this might have been fixed. Riding position worked a little funky in 1.20.2 to 1.20.4 because of mojang refactoring it (and changing it again in 1.20.5)

**Comment by VaraHunter682** [comment]
oh  lol ok

**Comment by Sollace** [comment]
Fixed in the most recent release
