### ISSUE TITLE
[BUG] ONLY ONE WING SHOWING

### ISSUE THREAD

**Issue by Mrufka69** [MineLittlePony/MineLittlePony#283]
**Describe the bug**
Only one wing showing. 

**Expected behavior**
Two wings will appear 

**Steps to reproduce**
Downloaded mods. 

**Screenshots**
![2024-06-14_16 40 37](https://github.com/MineLittlePony/MineLittlePony/assets/172260382/18b1aa8d-2312-44a4-97ab-197c2ac595fa)

**Version Information:**
 - Minecraft Version: 1.20.1
 - Mine Little Pony Version:

**Mod Loader:**
 -Fabric

**Client/Server Logs**
Just singleplayer

**Comment by MimzyFang** [comment]
Please provide the version number of minelp

**Comment by Mrufka69** [comment]
> Please provide the version number of minelp

Unicopia-1.3.6+1.20.1
minelittlepony-4.11.7+1.20.1

**Comment by Sollace** [comment]
Can you send the skin file you're using?

**Comment by Mrufka69** [comment]
![custtom_twi](https://github.com/MineLittlePony/MineLittlePony/assets/172260382/edbd689d-67b6-4d7e-a6f2-c64caa57d0fd)

btw im playing on paid minecraft version

**Comment by Sollace** [comment]
You're using the legacy skin format. We don't properly support those any more. Try converting it to the square skin using the tools on our website. https://minelittlepony-mod.com/tools/
