### ISSUE TITLE
[First Person Model] Sitting Animation Doesn't Look Quite Right

### ISSUE THREAD

**Issue by ModernSilver** [MineLittlePony/MineLittlePony#285]
Yep, this mod again. Seems like the sitting animation isn't working correctly with this mod. The camera is way too close to the body with fillycam ![2024-07-06_22 50 12](https://github.com/MineLittlePony/MineLittlePony/assets/42832475/fc47f298-2384-44a3-b51e-31fa9e432ff5) and little too far away without it. ![2024-07-06_22 50 40](https://github.com/MineLittlePony/MineLittlePony/assets/42832475/8a75eb1a-1f17-42bb-b5c1-ffd464124357)

If I were to hazard a guess, the model is either too big or in the wrong position for this animation. A first person v. third person comparision. ![2024-07-06_22 51 00](https://github.com/MineLittlePony/MineLittlePony/assets/42832475/99899dc0-54a4-4e95-85d8-b8397a4c38b5) ![2024-07-06_22 51 06](https://github.com/MineLittlePony/MineLittlePony/assets/42832475/8b19ef49-2eeb-4544-873f-bc8c1ce3bcf8) Side note: the hindlegs aren't visable when they probably should be for this animation specifically, don't see the wings either.

**Comment by Sollace** [comment]
(Should be) also fixed with the head position fix for Sit! mod.
