### ISSUE TITLE
Mobs not being ponified

### ISSUE THREAD

**Issue by TaigaP** [MineLittlePony/MineLittlePony#286]
Mobs do not appear as ponies despite all of the mob toggles being switched on in the mod's menu

**Steps to reproduce**
I loaded the game through Modrinth, with the modpack "Pony Craft a New Generation Vanilla" and 3 extra items (AstraLex Shaders, the Love and Tolerance texture pack, and ModMenu). I made sure all of the toggles were on for ponifying mobs and spawned multiple entites that would be affected. They retained their standard models. This has worked in prior versions with the same modpack.

**Screenshots**
![2024-07-26_01 46 18](https://github.com/user-attachments/assets/cbd453c0-8f7a-4096-9960-d39b47f279af)
![2024-07-26_01 27 42](https://github.com/user-attachments/assets/e067e0ce-472f-4b4f-a7fd-5cc545c0abfd)

**Version Information:**
 - Minecraft Version: 1.21
 - Mine Little Pony Version: 4.12.0+1.21

Mod Loader: Quilt

**Comment by MimzyFang** [comment]
As the maker of that modpack I am going to go investigate that

**Comment by keupoz** [comment]
Just letting you know, that disabling Bad Optimizations fixes this issue

**Comment by MimzyFang** [comment]
> Just letting you know, that disabling Bad Optimizations fixes this issue

Ah thanks

**Comment by Sollace** [comment]
People need to stop using Bad Optimisations...

**Comment by MimzyFang** [comment]
> People need to stop using Bad Optimisations...

That was on me sorry will update my pack today evening

**Comment by MimzyFang** [comment]
@TaigaP I updated the pack though if you have a issue while using the pack next time please report it [here](https://github.com/Fauli1221/PonyCraftANewGenerationVanilla/issues) thank you ^^
