### ISSUE TITLE
[BUG] Spyglass doesn't use the `HEAD` transform in third person

### ISSUE THREAD

**Issue by PixlRainbow** [MineLittlePony/MineLittlePony#293]
**Describe the bug**
When a resource pack which replaces the `spyglass_in_hand` model is applied, and the spyglass is used (right click), the transformation specified in `"display": { "head": { ... } }` is ignored and the transformation for `thirdperson_righthand`/`thirdperson_lefthand` is used instead.

In vanilla, the spyglass has a special transform `ModelTransformationMode.HEAD` which becomes active when the spyglass is being used in third person. However it appears Mine Little Pony is not using this transform as the base transform when it should.

**Expected behavior**
Custom spyglass switches to using the `HEAD` transform mode when spyglass is used; Mine Little Pony applies pony-specific transforms on top of custom transform specified for `"head"`.

**Steps to reproduce**
[Resource pack](https://github.com/user-attachments/files/17609785/iphone.spyglass.zip)

1. Apply the attached resource pack, which includes an exaggerated 4x scale transform for third person right hand, and a less obvious 1.6x scale transform for "head".
2. Switch to third person
3. Hold down right click while holding a spyglass in the right hand
4. Compare the difference appearance of the spyglass between human model and pony model by switching between "ponies only" and "humans only" in Mine Little Pony settings.

**Screenshots**
Human: [Screencast from 03-11-2024 16:24:17.webm](https://github.com/user-attachments/assets/af5f8991-2024-4561-b96c-5c3c98fa7fd9)
Pony: [Screencast from 03-11-2024 16:24:49.webm](https://github.com/user-attachments/assets/0cc64d2a-6626-4c04-876f-d52b8bbb1816)

**Version Information:**
 - Minecraft Version: 1.21
 - Mine Little Pony Version: 4.12.1+1.21 [Release]

**Mod Loader:**
 - [x] Fabric
 - [ ] Quilt
 - [ ] Neoforge (with connector)

**Comment by Sollace** [comment]
The head transform is for when an item is equipped to the helmet slot. We also do not pick the transform being applied, mojang does, so this has nothing to do with us.

**Comment by PixlRainbow** [comment]
> The head transform is for when an item is equipped to the helmet slot.

It doesn't change the fact that the built-in vanilla model _does_ specify a head transform (I have extracted the `spyglass_in_hand` model JSON from minecraft.jar to inspect it) and it _is_ being used by vanilla in a place other than the helmet slot.

Decompiling minecraft.jar indicates that the vanilla class method
- `net.minecraft.client.render.entity.feature.PlayerHeldItemFeatureRenderer::renderSpyglass`
  - calls `HeldItemRenderer::renderItem` with the transform parameter set to `HEAD`

**Comment by PixlRainbow** [comment]
It appears that you have replaced the vanilla `PlayerHeldItemFeatureRenderer` with a custom `HeldItemFeature` class extending from it, but didn't replace the special handling it performed for spyglasses.

**Comment by Sollace** [comment]
Fixed in 1.21.3
