### ISSUE TITLE
Neck renders upside down when sitting.

### ISSUE THREAD

**Issue by booblebobble** [MineLittlePony/MineLittlePony#3]
The neck shows up differently in the sitting pose than in any other pose (or in the editor on ponyskincraft).

![asdfsad](https://cloud.githubusercontent.com/assets/10958287/15419042/036c50ac-1e29-11e6-8ffd-e92590966ce4.png)

![daring do purple shirt-converted](https://cloud.githubusercontent.com/assets/10958287/15419061/2219a1ee-1e29-11e6-9056-7fe5005f26a9.png)

**Comment by killjoy1221** [comment]
Should be fixed
