### ISSUE TITLE
Armor slots behaving oddly

### ISSUE THREAD

**Issue by lunapanshiel** [MineLittlePony/MineLittlePony#31]
simply put, when i put on a piece of body armor, it doesn't display, but when i put on leggings, the body+legs display together, not separately. body slot armors are currently not displaying their graphic

using the latest 1.11.2 version plus optifine

**Comment by killjoy1221** [comment]
It all works for me. This is what the body armor looks like.
![image](https://cloud.githubusercontent.com/assets/3409962/25197596/9de3ad38-2512-11e7-9030-c73a8f8c7ab9.png)
This is leggings
![image](https://cloud.githubusercontent.com/assets/3409962/25197631/b5eefe46-2512-11e7-8d1e-808a235b897d.png)

If you don't like how they are, you can change it with a resource pack.

**Comment by lunapanshiel** [comment]
no you don't understand, when i equip a body slot armor, -nothing- shows up, at all, nothing displays, period, but when i equip PANTS, then body AND legs show up together, as one piece

**Comment by killjoy1221** [comment]
What it's supposed to look like and what it used to look like are two separate things. Armor has been buggy like that since I rewrote it for 1.8. I recently got it working right, so if a resource pack was made using the buggy model, the author should fix it.
