### ISSUE TITLE
Unable to upload skins to server

### ISSUE THREAD

**Issue by Ryvaken** [MineLittlePony/MineLittlePony#32]
For the past couple days the F1 screen to change skins has been unable to retrieve or update skins from the server. The game simply says it's waiting on the server.

Myself and others still appear as ponies with the correct skins in-game.

Tested with 1.11.2 and 1.7.10 versions.

**Comment by killjoy1221** [comment]
Seems the server is down. Nothing I can do about it. You'll have to wait for it to come back up.

**Comment by killjoy1221** [comment]
Got mumfrey to reboot the server. All's good.
