### ISSUE TITLE
Bug in the recognition.

### ISSUE THREAD

**Issue by robocart9** [MineLittlePony/MineLittlePony#34]
I don't know why but when I download it my computer doesn't recognize it and cant open/launch/use this file. The icon is a Blank Page. I'm just concerned if I have to download something else or do something with it that I am not getting but can you please help me with this?

**Comment by robocart9** [comment]
this is a picture of what the file looks like
![capture](https://user-images.githubusercontent.com/29615110/27502752-75c77928-5844-11e7-8b7c-466c2645bbd0.PNG)

**Comment by robocart9** [comment]
another picture, this type after downloading the file.
![capture](https://user-images.githubusercontent.com/29615110/27502921-b8433a5c-5845-11e7-8cd9-93e638ccce75.PNG)

**Comment by killjoy1221** [comment]
Read the install instructions.
http://minelittlepony-mod.com/installation/
