### ISSUE TITLE
Crash when loading at newest Liteloader snapshot [1.12]

### ISSUE THREAD

**Issue by hectorwilde** [MineLittlePony/MineLittlePony#35]
Hello when i put, MineLP on the new LiteLoader snapshot for 1.12 i get error with not found a class.
Here is log:
https://pastebin.com/jT3snxch
I don't know maybe its LiteLoader Issue. :face_with_head_bandage:

**Comment by killjoy1221** [comment]
Yup. Seems to happen for me as well.

@Mumfrey ?

**Comment by killjoy1221** [comment]
Download here. https://github.com/MineLittlePony/MineLittlePony/releases/tag/1.12.0.2

**Comment by hectorwilde** [comment]
And still have problem with implementation.
Here go log, i tried fix it myself with code but no luck:
https://pastebin.com/raw/ASgSXuiw (logs are from your version)

**Comment by killjoy1221** [comment]
Looks like the mixin refmaps are missing from the litemod file. I'll try to fix soon.
