### ISSUE TITLE
It crashes when using forge and liteloader

### ISSUE THREAD

**Issue by MidnightRose** [MineLittlePony/MineLittlePony#37]
It work fine with liteloder but it crashes when using forge and liteloader and I have the new verion

**Comment by killjoy1221** [comment]
please provide a crash report, as well as any other useful data. (OS, forge version, liteloader version, minelp version)

**Comment by HectorWilde** [comment]
It's the same problem like me.

**Comment by killjoy1221** [comment]
This is a bad example of an issue. I'll fix the issue anyway though because I found it on my own
