### ISSUE TITLE
How exactly do I download the mod? 

### ISSUE THREAD

**Issue by DoughnutQuest123** [MineLittlePony/MineLittlePony#43]
I've been trying to download this mod for days now. I just can't seem to understand how to download it! Please help me if you possibly can.

**Comment by killjoy1221** [comment]
The download button on the website should take you to the latest version on github (releases tab), which is currently [1.12.2.1](../releases/1.12.2.1).

On that page is some links. 2 of them are source links. Ignore those. You want the one which ends with `.litemod`. Click it to download it. Afterwards, put it in your mods folder.

See the [install](http://www.minelittlepony-mod.com/installation/) help for more help.

**Comment by DoughnutQuest123** [comment]
Thank you so much! I'm really enjoying the mod too!
