### ISSUE TITLE
Console Spam when opening the skins tab [1.10.2]

### ISSUE THREAD

**Issue by Gh0st-VX** [MineLittlePony/MineLittlePony#44]
Upon opening the submenu where you can change your skin, the multiMC log is filled with the same error message until closed.
https://paste.ee/p/IFR7s

This does not occur with 1.12.2.

**Comment by killjoy1221** [comment]
If this does not occur in 1.12.2, that means it was a bug that I fixed. I
believe the workaround was to join a server or world beforehand.

**Comment by Gh0st-VX** [comment]
Joining a world and then opening the submenu still causes the console spam. But if worst comes to worst, you can change the skin, then close and reopen minecraft.

**Comment by Sollace** [comment]
Old version and console paste no longer exists. Shall I close this as invalid? I think I will.
