### ISSUE TITLE
delay in updating ingame skin

### ISSUE THREAD

**Issue by LuckyDusk** [MineLittlePony/MineLittlePony#5]
So every time I upload a new skin, it takes awhile to update in game. I'm not 100% sure when this started but I think it was around the time the voxel team took over, and it seems I'm still having it to today.

Also this is the reply I got when I asked about 2 years ago 

"It's probably on your end since I don't have any issues with the skin server. It may also be temporary. But when the skin shows up at all without you doing anything, that means it is working, only the downloading of the skin takes long for whatever reason"

.

**Comment by killjoy1221** [comment]
This isn't something I can easily fix client-side. I suspect it's related to cloudflare caching, but @Mumfrey says it gets invalidated, but I've seen that it works just fine using the default server (skins.voxelmodpack.com vs minelpskins.voxelmodpack.com)

**Comment by LuckyDusk** [comment]
Is there a way to switch servers?

**Comment by killjoy1221** [comment]
Not using a config option. You would have to comment out some lines from MineLittlePony to prevent it from resetting the skin server.

**Comment by LuckyDusk** [comment]
What do I need to do that?

**Comment by EPSIL0N** [comment]
1.10.2 I'm having an issue where my client side skin when I press f5 is not reflecting updates but other players see my 'newer' skin that I've uploaded. Going on >48 hours now.
Is there some file I need to clear to force an update on my end?

**Comment by killjoy1221** [comment]
@EPSIL0N Not really related, but you can try deleting `.minecraft/assets/skins`

**Comment by EPSIL0N** [comment]
No clue if I fixed the issue on my end by any particular action but I updated my steve skin using the mincraft site to a different human skin and then pushed a new pony skin to the pony skin server from in game and that seemed to trigger it to actually refresh.

**Comment by killjoy1221** [comment]
Should be better with 486f787db39669464c2dc378698296b01c4d2d20. This should be in the 1.12.1.0-pre release

**Comment by killjoy1221** [comment]
I'm slowly working on this at https://github.com/killjoy1221/mcskinserver/tree/flask

Stay tuned.

**Comment by Sollace** [comment]
@LuckyDusk I've just pushed several fixes for skin related bugs, so we should probably check if this bug is still present and close if not.

**Comment by killjoy1221** [comment]
Is this still an issue in the latest version?

**Comment by PolyacovYury** [comment]
Well, we need to get @LuckyDusk's attention somehow. At the moment the delay is negligible and highly relies on user's Internet connection.

**Comment by killjoy1221** [comment]
Should be fixed. Can't guarantee for legacy skin server, but should be fine using the new one.
