### ISSUE TITLE
"Use show-accurate scaling" is broken

### ISSUE THREAD

**Issue by seajaygreeny** [MineLittlePony/MineLittlePony#51]
was broken after https://github.com/MineLittlePony/MineLittlePony/commit/694db391bb7fa35ba9c2d9982ba1d8bc6801295e
![image](https://user-images.githubusercontent.com/23411818/40279320-d216868a-5c83-11e8-9096-1dd65d65e6c8.png)

![image](https://user-images.githubusercontent.com/23411818/40279314-bc367bd6-5c83-11e8-8d5b-b897ed511485.png)
(changes only shadow, model is not changes.)

**Comment by Sollace** [comment]
Eeyup, can confirm. I'd noticed that in testing, and may have an idea what it is.

**Comment by seajaygreeny** [comment]
Thank you, guys!
