### ISSUE TITLE
[Enhancement] Villager bags for players using a new separate race pixel colour

### ISSUE THREAD

**Issue by PolyacovYury** [MineLittlePony/MineLittlePony#54]
In [MC4EP](http://mc4ep.ru/)'s fork of the mod we (well, I :P) added a "villager" race for players. Essentially, it's a properly registered copy of ModelVillagerPony, which adds bags instead of wings, but with cut out trinkets and aprons. Maybe would take a look at properly implementing this? (I'm an earth pony and I really want dem bags :D)
If you're interested - 0x8BDC94 is for an earth pony with bags, 0xC65FA3 - unicorn with bags.
Dropping off race pixel values here so that when an update rolls out, we wouldn't have to re-draw our skins again ^^

@Sollace Sounds nice. I'd considered an idea of implementing "accessories." Essentially you' have a trigger pixel that lets you specify whether your pony is wearing any one of the villager's equipment or the Witche's hat
The issue, though, is that you wouldn't be able to skin these items. I don't know if we have space on the regular skin.

Well, I would say that aprons and trinkets are kinda unnecessary, since you have the second layer of a skin in new layout anyway. And since converting a skin to a new layout is a matter of 5 minutes of work in Paint.NET, overloading player's model code with support of that stuff is kind of unnecessary.
But the bags are different. They actually replace your wings.

A thought just crossed my mind. We do have some open space on new skin layout, right? Maybe we could add big saddle bags that would replace model's wings, as described above, and small ones, that would go below the wings or behind them, closer to the rear part (and would be drawn on one of remaining free spots of the skin)? And obviously add a toggle for all this stuff, since a unicorn might want dem bags be small as well.

My idea is to add two additional races (villager and villager-unicorn) with big bags and a trigger pixel with an area for drawing for small ones.
Small are optional, big are urgent :D

**Comment by Sollace** [comment]
@PolyacovYury I still disagree on creating entire new races for the saddlebags. It's messy and not really extensible, as you'd already illustrated with the "villager" and "villager-unicorn." To cover all possible combinations, there'd also have to be a "villager-pegasus," "villager-alicorn," "villager-changeling," etc.

That's why I suggested a separate trigger pixel for saddlebags on their own. Then whichever race you are, you can choose whether to have them or not.

The catch-22 is that we can't use any spaces reserved for the wings or for any parts the other races use. I don't know if there's enough space on the texture to fit them. (I'd be more than happy to be proven wrong here.)

Alternatively, what's the possibility of being able to upload an additional texture to the skin server? We could then texture them similarly to elytra, or piggy-back on the empty spaces on the elytra's texture.

**Comment by PolyacovYury** [comment]
Well, AFAIK changelings and other things are just copies of an alicorn.
And there would be no such thing as a "villager-pegasus" (or "villager-any-race-with-wings") because big bags not only use the space reserved for wings, but also entirely cover them up on a model. While testing, I accidentally left wings on "my" villagers enabled, and that didn't look good at all.
Those are two reasons why I am suggesting adding ponies with big bags as a separate race.

Small bags (designed for pegasi, usable by everyone), however, should indeed have a separate space on texture as well as a trigger pixel, no arguing here.

**Comment by Sollace** [comment]
@PolyacovYury You're missing the point. I don't want to be  _race pixel_, I want it to have it _own pixel_. Otherwise we'd have to keep adding more races for bags whenever we want to add bags to any of the existing or future races.

**Comment by Sollace** [comment]
You also don't see Applejack going around shouting "Ah'm a Saddlebag Pony!" every time she gets dressed to travel, however cute that would be.

**Comment by PolyacovYury** [comment]
...I seem to get it now. But do you understand that if a winged pony activates "big" bags on him - his wings would have to go? There is no way we could fit "big" bags **and** wings on skins at the same time.
This is the problem I'm solving with a separate race - so we don't need to handle wings and bags at the same time. Wings and "big" bags are mutually exclusive atm.

Small bags are a totally different story, however. We could fit them anywhere else, so they don't contradict with any existing details.

**Comment by PolyacovYury** [comment]
```
if we're going to do this I'd want everypony to be able to wear the same size bags and not have to make a new model.```
Well, then someone would have to re-design the bags completely. Right now it looks like wings are hidden inside the bags when folded. ~If you paint them red with black dots - and we get a ladybug pony with elytra that actually cover the wings lol~ I don't see how you would add currently implemented saddle bags for pegasi without them intersecting with wings and looking awkward.

We still could switch between wings and bags with a separate trigger pixel, though. If a pixel is not set - render wings. If it is filled with colour (e,g. something leather-like) - render bags instead. This way we utilise an already existing system without a total rewrite of a bunch of stuff.
