### ISSUE TITLE
If human skin on Minecraft.net is for Alex model, pony server skin is forced to use Alex as well

### ISSUE THREAD

**Issue by Febilian** [MineLittlePony/MineLittlePony#6]
...Which kind of messes up my skin a LOT when showing both humans/ponies is enabled. It's a little unsettling.

https://gyazo.com/39ca41562159e35f7c0eee998a5f5083

It seems to be trying to grab my normal player skin instead of the pony skin I have uploaded(which looks fine in the preview screen for the record).

Changing the ponify option back to just ponies(i.e. the default option) and restarting MC gives me the default pony skin(Daring Do) with slim arms instead.

EDIT: Turns out the human-turned-pony nonsense was actually just me having tried to get a wrongly-formatted skin working earlier with the override functions introduced recently, now if I re-create the same scenario with that completely disabled, it just uses my human skin(which is using the Alex model) without trying to turn it into a pony at all. Still not really what I wanted though.

EDIT 2: Can't believe I forgot to add that I'm using the 1.9.4 version from the forum thread....

**Comment by killjoy1221** [comment]
@Sollace What's the status of this?

**Comment by Sollace** [comment]
@killjoy1221 I think this should have been fixed with your metadata changes. At the vert least, the skin preview seems to work the last I checked.

**Comment by killjoy1221** [comment]
Fixed I guess.
