### ISSUE TITLE
No way to update skin cache without restarting game client

### ISSUE THREAD

**Issue by PolyacovYury** [MineLittlePony/MineLittlePony#60]
Well, the title says it. Changed my race from earth pony to unicorn. I couldn't see the changes until I restarted the game client - "Clear skin cache" button and relogin not doing anything - and a friend of mine tried all combinations of relogging and pressing the button too. If you want to see player's new skin - only way is to completely restart the game.
This is crucial for moderating our MC server - a moderator would have to constantly restart the game to see if a player with an inappropriate skin has actually changed it to something more reasonable. Instead of pressing a conveniently provided, but clearly broken button in LiteLoader menu.

**Comment by PolyacovYury** [comment]
Further testing indicates that clearing skin cache actually helps updating your own skin, but not completely. Player renderer seems to get stuck on a specific race and height. Updated from a filly pegasus to big earth pony - stayed as filly pegasus but with a new texture.

**Comment by Sollace** [comment]
I suspect clearing the skin cache should also clear the PonyData values as well. That might be where the skins are getting stuck.

**Comment by PolyacovYury** [comment]
Tested with a friend again. The skin itself got updated - cut out a part of a wing - after "Clear skin cache" button press. But metadata info doesn't update, so you seem to be right.
