### ISSUE TITLE
Player's camera not centered on player model's head after shadow position fix

### ISSUE THREAD

**Issue by PolyacovYury** [MineLittlePony/MineLittlePony#66]
Recent "fix" for shadows was done by moving pony models forward. And even though this doesn't look more illogical than what we had before (current system actually looks a tiny bit better), there is a problem with player's camera position.
To put this simply, it isn't placed in model's head center anymore. My suggestion would be either moving the camera to match model's movement or moving the model to its previous location.
Since mc4ep has a mod in development that moves player's camera downwards depending on pony's height, I would suggest the first option. However it may be harder to implement and less cross-compatible.

**Comment by Sollace** [comment]
>Since mc4ep has a mod in development that moves player's camera downwards depending on pony's height, 

You haven't heard of Big Pony? We already have a mod for that.

**Comment by PolyacovYury** [comment]
Asked them about it. :) But having yet another separate view point tweaker mod only proves my point event more, don't you think?

**Comment by killjoy1221** [comment]
I have humored the idea of merging that mod into this one. Maybe in the future.

**Comment by Sollace** [comment]
It would be useful to have them together. Butt on the matter of merging mods, why don't we have HDskins as a separate mod?

**Comment by PolyacovYury** [comment]
Well, after merging it would still need to be made disableable.

**Comment by killjoy1221** [comment]
I have also thought about that. Conversation on that topic belongs in #40
