### ISSUE TITLE
Mod still being developed?

### ISSUE THREAD

**Issue by xana43** [MineLittlePony/MineLittlePony#72]
I'm making this thread here to ask, is this mod still being developed, I know that this mod MAY be ported to 1.13 (when it comes out) but it might not, I don't know, the future of this mod in still kind of unknown. All i'm asking is, is this mod still being actively developed, and if not, will there be anyone else coming to help develop it (I would help, but my java programming is kind of awful, especially when it comes to editing the player class)

**Comment by killjoy1221** [comment]
The last commit was earlier this week. You can see this from the network
graph in insights.

**Comment by xana43** [comment]
I feel kind of dumb now
