### ISSUE TITLE
Should HDSkins be moved to is own project?

### ISSUE THREAD

**Issue by Sollace** [MineLittlePony/MineLittlePony#84]
Making an issue for this so we can discuss. Right now HDSkins has its own package, and it lives as a sort of festering tumur inside the MineLittlePony repo.

There's been mention of splitting it off that I thought would be a great idea. Related to that, should the package name it uses be changed as well?

Right now it's more of a legacy thing than anything else, and a bit misleading considering it's no longer being maintained by the voxel team and KillJay has stated himself that he's done a full rewrite of the original mod.

My idea is that the `come.voxelmodpack.hdskins` package could be renamed to `com.minelittlepony.hdskins` with the accompanying `com.minelittlepony.gui` becoming `com.minelittlepony.lib.gui` to signify being a shared package.

**Comment by Sollace** [comment]
P.S. This would also coincide with a full reshuffling of the hdskins packages that I previously had in my branch, but threw out due to whining.

**Comment by derram** [comment]
What would be the result for people who don't have it installed when they come across another user who has an HD skin or would they still come bundled and this is just for making the coding easier?

**Comment by Sollace** [comment]
This is just more for making developing the mods easier. At the very worst people installing two litemods instead of once, since Mine Little pony would still require HDSkins for something things.

**Comment by Superplay64** [comment]
Would it make more sense to _fully_ integrate it into MineLP?  If not, would there be another to keep the two together in the same mod file?
I feel like it might be easier for naive players, who don't understand mods too well, to not need to install two files.  Could lead to them constantly saying "nu, u just dont hav a skin", when you're trying to tell them that they're missing a mod, and they don't realize there is a separate mod for _HD_ skins.  (That is, if you were planning to release them as two separate mods that were not directly dependent on one another.)

**Comment by killjoy1221** [comment]
Releasing as separate mods would simplify the release process and versioning for each. I've already split the hdskins portion out at https://github.com/MineLittlePony/HDSkins if you want to take a look.

**Comment by Sollace** [comment]
Closed. The answer is YES!
