### ISSUE TITLE
Unicorn magic doesn't outline shields properly while blocking

### ISSUE THREAD

**Issue by MyUsernameDoesntMatter** [MineLittlePony/MineLittlePony#9]
As shown here.
![2016-07-03_20 17 01](https://cloud.githubusercontent.com/assets/20265984/16545151/48681136-415c-11e6-825a-09d463faecb4.png)

**Comment by killjoy1221** [comment]
That seems to fix it. I think the problem was it was checking if the specific itemstack was in the inventory, but since it was copied, it was not.
