### ISSUE TITLE
Arm position and appearance in first person is very different to how it used to be.

### ISSUE THREAD

**Issue by PolyacovYury** [MineLittlePony/MineLittlePony#90]
The good old one:
![img](https://cdn.discordapp.com/attachments/403599968541081611/462650438978633739/2018-04-20_13.10.17.png)

The new one:
![img](https://cdn.discordapp.com/attachments/403599968541081611/462637634867429401/2018-06-30_18.04.34.png)

I'm not saying it's necessarily bad, it's just *not how it used to be*. If it's not that hard - we maybe should make this an option in the config.

On topic of first-person arm appearance: maybe we can also add an option - something like "Show-accurate first-person arm rotation" - and if that option is enabled - first-person arm gets rotated so that the foremost side is facing upwards instead of current outer one. I suggested this in chat and it kinda drifted off...

**Comment by Sollace** [comment]
This cannot be made an option. The old code that did that (read 12 armed heptiponies) was deleted.

**Comment by PolyacovYury** [comment]
Can't we detect or determine, whether is the arm being rendered in first person or not?

**Comment by Sollace** [comment]
There is only one arm. It just has to be transformed to the right position.

**Comment by PolyacovYury** [comment]
And that position can be calculated depending on config option(s), can't it?

**Comment by Sollace** [comment]
It will be by default as close to the regular arm as we can get. The problem is that certain skin types change the shape and position of the arm.

**Comment by PolyacovYury** [comment]
Feels like having a separate hand for first person had a good reason...
