### ISSUE TITLE
MineLP 1.12.2.3-beta and VanillaFix conflict somehow

### ISSUE THREAD

**Issue by KandiPanda** [MineLittlePony/MineLittlePony#97]
MineLP 1.12.2.1 and [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix) (currently using VanillaFix-1.0.9-97) work fine together.

Upgrading MineLP to 1.12.2.3-beta causes it to crash before the "Minecraft 1.12.2" window even appears on the screen. Reverting MineLP OR removing VanillaFix solves the problem and allows Minecraft to operate as usual.

[latest.log](https://github.com/MineLittlePony/MineLittlePony/files/2408368/latest.log)

**Comment by killjoy1221** [comment]
Conflicting mixin
https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/vanillafix/crashes/mixins/client/MixinMinecraft.java#L276

Easy fix would be to increase the priority for our mixin.

**Comment by Sollace** [comment]
VanillaFix is using an @ovewrite. That's inherently not very good practice. I will try killy's suggestion of changing priorities

**Comment by Sollace** [comment]
Pinging the author of VanillaFix for this. Crash should be fixed. @Runemoro, you should consider rewriting your mixins to reduce the amount of injected code, and avoid overwriting existing methods.
