### ISSUE TITLE
Change batpony trigger pixel to 0xeeeeee

### ISSUE THREAD

**Issue by killjoy1221** [MineLittlePony/MineLittlePony#99]
![image](https://user-images.githubusercontent.com/3409962/47055103-ce7cb380-d183-11e8-8e04-75d0d3594868.png)

Really, I'm ashamed you didn't do that in the first place.

Creating an issue instead of just doing it because skins need to be updated.

**Comment by ArcadeZero** [comment]
I agree wholeheartedly with this
